package com.wecloud.erp.model;

public class CustomerType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customertype.ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customertype.NAME
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customertype.CATEGORY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String category;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customertype.ID
	 * @return  the value of customertype.ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customertype.ID
	 * @param id  the value for customertype.ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customertype.NAME
	 * @return  the value of customertype.NAME
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customertype.NAME
	 * @param name  the value for customertype.NAME
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customertype.CATEGORY
	 * @return  the value of customertype.CATEGORY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customertype.CATEGORY
	 * @param category  the value for customertype.CATEGORY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCategory(String category) {
		this.category = category == null ? null : category.trim();
	}
}