package com.wecloud.erp.model;

public class CustomerView {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customerview.id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customerview.code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customerview.name
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customerview.category
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String category;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customerview.type
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customerview.payment_amount
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Double paymentAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customerview.status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customerview.contact_name
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String contactName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customerview.contact_cellphone
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String contactCellphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customerview.contact_phone
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String contactPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customerview.contact_im
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String contactIm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customerview.contact_address
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String contactAddress;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customerview.id
	 * @return  the value of customerview.id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customerview.id
	 * @param id  the value for customerview.id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customerview.code
	 * @return  the value of customerview.code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customerview.code
	 * @param code  the value for customerview.code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customerview.name
	 * @return  the value of customerview.name
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customerview.name
	 * @param name  the value for customerview.name
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customerview.category
	 * @return  the value of customerview.category
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customerview.category
	 * @param category  the value for customerview.category
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCategory(String category) {
		this.category = category == null ? null : category.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customerview.type
	 * @return  the value of customerview.type
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customerview.type
	 * @param type  the value for customerview.type
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customerview.payment_amount
	 * @return  the value of customerview.payment_amount
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Double getPaymentAmount() {
		return paymentAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customerview.payment_amount
	 * @param paymentAmount  the value for customerview.payment_amount
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setPaymentAmount(Double paymentAmount) {
		this.paymentAmount = paymentAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customerview.status
	 * @return  the value of customerview.status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customerview.status
	 * @param status  the value for customerview.status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customerview.contact_name
	 * @return  the value of customerview.contact_name
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getContactName() {
		return contactName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customerview.contact_name
	 * @param contactName  the value for customerview.contact_name
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setContactName(String contactName) {
		this.contactName = contactName == null ? null : contactName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customerview.contact_cellphone
	 * @return  the value of customerview.contact_cellphone
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getContactCellphone() {
		return contactCellphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customerview.contact_cellphone
	 * @param contactCellphone  the value for customerview.contact_cellphone
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setContactCellphone(String contactCellphone) {
		this.contactCellphone = contactCellphone == null ? null : contactCellphone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customerview.contact_phone
	 * @return  the value of customerview.contact_phone
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getContactPhone() {
		return contactPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customerview.contact_phone
	 * @param contactPhone  the value for customerview.contact_phone
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone == null ? null : contactPhone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customerview.contact_im
	 * @return  the value of customerview.contact_im
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getContactIm() {
		return contactIm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customerview.contact_im
	 * @param contactIm  the value for customerview.contact_im
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setContactIm(String contactIm) {
		this.contactIm = contactIm == null ? null : contactIm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customerview.contact_address
	 * @return  the value of customerview.contact_address
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getContactAddress() {
		return contactAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customerview.contact_address
	 * @param contactAddress  the value for customerview.contact_address
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setContactAddress(String contactAddress) {
		this.contactAddress = contactAddress == null ? null : contactAddress.trim();
	}
}