package com.wecloud.erp.model;

import java.util.Date;

public class DeliveryRequest {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deliveryrequest.id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deliveryrequest.code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deliveryrequest.type
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deliveryrequest.created_by
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deliveryrequest.creator
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String creator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deliveryrequest.qty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Double qty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deliveryrequest.created_on
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Date createdOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deliveryrequest.delivery_date
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Date deliveryDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deliveryrequest.so_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String soId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deliveryrequest.reference_no
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String referenceNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deliveryrequest.status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deliveryrequest.approval_status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String approvalStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deliveryrequest.pmc_status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String pmcStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deliveryrequest.d_approver_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String dApproverId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deliveryrequest.d_approver
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String dApprover;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deliveryrequest.d_approval_status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String dApprovalStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deliveryrequest.name
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deliveryrequest.checkoutrec_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String checkoutrecId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deliveryrequest.description
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deliveryrequest.id
	 * @return  the value of deliveryrequest.id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column deliveryrequest.id
	 * @param id  the value for deliveryrequest.id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deliveryrequest.code
	 * @return  the value of deliveryrequest.code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column deliveryrequest.code
	 * @param code  the value for deliveryrequest.code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deliveryrequest.type
	 * @return  the value of deliveryrequest.type
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column deliveryrequest.type
	 * @param type  the value for deliveryrequest.type
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deliveryrequest.created_by
	 * @return  the value of deliveryrequest.created_by
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column deliveryrequest.created_by
	 * @param createdBy  the value for deliveryrequest.created_by
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy == null ? null : createdBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deliveryrequest.creator
	 * @return  the value of deliveryrequest.creator
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column deliveryrequest.creator
	 * @param creator  the value for deliveryrequest.creator
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCreator(String creator) {
		this.creator = creator == null ? null : creator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deliveryrequest.qty
	 * @return  the value of deliveryrequest.qty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Double getQty() {
		return qty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column deliveryrequest.qty
	 * @param qty  the value for deliveryrequest.qty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setQty(Double qty) {
		this.qty = qty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deliveryrequest.created_on
	 * @return  the value of deliveryrequest.created_on
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Date getCreatedOn() {
		return createdOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column deliveryrequest.created_on
	 * @param createdOn  the value for deliveryrequest.created_on
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deliveryrequest.delivery_date
	 * @return  the value of deliveryrequest.delivery_date
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Date getDeliveryDate() {
		return deliveryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column deliveryrequest.delivery_date
	 * @param deliveryDate  the value for deliveryrequest.delivery_date
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setDeliveryDate(Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deliveryrequest.so_id
	 * @return  the value of deliveryrequest.so_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getSoId() {
		return soId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column deliveryrequest.so_id
	 * @param soId  the value for deliveryrequest.so_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setSoId(String soId) {
		this.soId = soId == null ? null : soId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deliveryrequest.reference_no
	 * @return  the value of deliveryrequest.reference_no
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getReferenceNo() {
		return referenceNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column deliveryrequest.reference_no
	 * @param referenceNo  the value for deliveryrequest.reference_no
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setReferenceNo(String referenceNo) {
		this.referenceNo = referenceNo == null ? null : referenceNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deliveryrequest.status
	 * @return  the value of deliveryrequest.status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column deliveryrequest.status
	 * @param status  the value for deliveryrequest.status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deliveryrequest.approval_status
	 * @return  the value of deliveryrequest.approval_status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getApprovalStatus() {
		return approvalStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column deliveryrequest.approval_status
	 * @param approvalStatus  the value for deliveryrequest.approval_status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setApprovalStatus(String approvalStatus) {
		this.approvalStatus = approvalStatus == null ? null : approvalStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deliveryrequest.pmc_status
	 * @return  the value of deliveryrequest.pmc_status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getPmcStatus() {
		return pmcStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column deliveryrequest.pmc_status
	 * @param pmcStatus  the value for deliveryrequest.pmc_status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setPmcStatus(String pmcStatus) {
		this.pmcStatus = pmcStatus == null ? null : pmcStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deliveryrequest.d_approver_id
	 * @return  the value of deliveryrequest.d_approver_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getdApproverId() {
		return dApproverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column deliveryrequest.d_approver_id
	 * @param dApproverId  the value for deliveryrequest.d_approver_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setdApproverId(String dApproverId) {
		this.dApproverId = dApproverId == null ? null : dApproverId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deliveryrequest.d_approver
	 * @return  the value of deliveryrequest.d_approver
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getdApprover() {
		return dApprover;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column deliveryrequest.d_approver
	 * @param dApprover  the value for deliveryrequest.d_approver
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setdApprover(String dApprover) {
		this.dApprover = dApprover == null ? null : dApprover.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deliveryrequest.d_approval_status
	 * @return  the value of deliveryrequest.d_approval_status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getdApprovalStatus() {
		return dApprovalStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column deliveryrequest.d_approval_status
	 * @param dApprovalStatus  the value for deliveryrequest.d_approval_status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setdApprovalStatus(String dApprovalStatus) {
		this.dApprovalStatus = dApprovalStatus == null ? null : dApprovalStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deliveryrequest.name
	 * @return  the value of deliveryrequest.name
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column deliveryrequest.name
	 * @param name  the value for deliveryrequest.name
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deliveryrequest.checkoutrec_id
	 * @return  the value of deliveryrequest.checkoutrec_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getCheckoutrecId() {
		return checkoutrecId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column deliveryrequest.checkoutrec_id
	 * @param checkoutrecId  the value for deliveryrequest.checkoutrec_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCheckoutrecId(String checkoutrecId) {
		this.checkoutrecId = checkoutrecId == null ? null : checkoutrecId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deliveryrequest.description
	 * @return  the value of deliveryrequest.description
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column deliveryrequest.description
	 * @param description  the value for deliveryrequest.description
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}
}