package com.wecloud.erp.model;

public class ErpRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column erprole.ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column erprole.USER_ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column erprole.role
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String role;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column erprole.ID
	 * @return  the value of erprole.ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column erprole.ID
	 * @param id  the value for erprole.ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column erprole.USER_ID
	 * @return  the value of erprole.USER_ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column erprole.USER_ID
	 * @param userId  the value for erprole.USER_ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column erprole.role
	 * @return  the value of erprole.role
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column erprole.role
	 * @param role  the value for erprole.role
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setRole(String role) {
		this.role = role == null ? null : role.trim();
	}
}