package com.wecloud.erp.model;

import java.util.Date;

public class Faulty {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column faulty.id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column faulty.code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column faulty.type
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column faulty.created_by
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column faulty.creator
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String creator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column faulty.qty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Double qty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column faulty.created_on
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Date createdOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column faulty.reference_no
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String referenceNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column faulty.status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column faulty.approval_status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String approvalStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column faulty.pmc_status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String pmcStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column faulty.d_approver_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String dApproverId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column faulty.d_approver
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String dApprover;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column faulty.d_approval_status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String dApprovalStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column faulty.supplier_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String supplierId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column faulty.description
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column faulty.id
	 * @return  the value of faulty.id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column faulty.id
	 * @param id  the value for faulty.id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column faulty.code
	 * @return  the value of faulty.code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column faulty.code
	 * @param code  the value for faulty.code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column faulty.type
	 * @return  the value of faulty.type
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column faulty.type
	 * @param type  the value for faulty.type
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column faulty.created_by
	 * @return  the value of faulty.created_by
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column faulty.created_by
	 * @param createdBy  the value for faulty.created_by
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy == null ? null : createdBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column faulty.creator
	 * @return  the value of faulty.creator
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column faulty.creator
	 * @param creator  the value for faulty.creator
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCreator(String creator) {
		this.creator = creator == null ? null : creator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column faulty.qty
	 * @return  the value of faulty.qty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Double getQty() {
		return qty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column faulty.qty
	 * @param qty  the value for faulty.qty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setQty(Double qty) {
		this.qty = qty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column faulty.created_on
	 * @return  the value of faulty.created_on
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Date getCreatedOn() {
		return createdOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column faulty.created_on
	 * @param createdOn  the value for faulty.created_on
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column faulty.reference_no
	 * @return  the value of faulty.reference_no
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getReferenceNo() {
		return referenceNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column faulty.reference_no
	 * @param referenceNo  the value for faulty.reference_no
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setReferenceNo(String referenceNo) {
		this.referenceNo = referenceNo == null ? null : referenceNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column faulty.status
	 * @return  the value of faulty.status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column faulty.status
	 * @param status  the value for faulty.status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column faulty.approval_status
	 * @return  the value of faulty.approval_status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getApprovalStatus() {
		return approvalStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column faulty.approval_status
	 * @param approvalStatus  the value for faulty.approval_status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setApprovalStatus(String approvalStatus) {
		this.approvalStatus = approvalStatus == null ? null : approvalStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column faulty.pmc_status
	 * @return  the value of faulty.pmc_status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getPmcStatus() {
		return pmcStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column faulty.pmc_status
	 * @param pmcStatus  the value for faulty.pmc_status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setPmcStatus(String pmcStatus) {
		this.pmcStatus = pmcStatus == null ? null : pmcStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column faulty.d_approver_id
	 * @return  the value of faulty.d_approver_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getdApproverId() {
		return dApproverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column faulty.d_approver_id
	 * @param dApproverId  the value for faulty.d_approver_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setdApproverId(String dApproverId) {
		this.dApproverId = dApproverId == null ? null : dApproverId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column faulty.d_approver
	 * @return  the value of faulty.d_approver
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getdApprover() {
		return dApprover;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column faulty.d_approver
	 * @param dApprover  the value for faulty.d_approver
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setdApprover(String dApprover) {
		this.dApprover = dApprover == null ? null : dApprover.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column faulty.d_approval_status
	 * @return  the value of faulty.d_approval_status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getdApprovalStatus() {
		return dApprovalStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column faulty.d_approval_status
	 * @param dApprovalStatus  the value for faulty.d_approval_status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setdApprovalStatus(String dApprovalStatus) {
		this.dApprovalStatus = dApprovalStatus == null ? null : dApprovalStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column faulty.supplier_id
	 * @return  the value of faulty.supplier_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getSupplierId() {
		return supplierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column faulty.supplier_id
	 * @param supplierId  the value for faulty.supplier_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setSupplierId(String supplierId) {
		this.supplierId = supplierId == null ? null : supplierId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column faulty.description
	 * @return  the value of faulty.description
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column faulty.description
	 * @param description  the value for faulty.description
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}
}