package com.wecloud.erp.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class FaultyExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table faulty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table faulty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table faulty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table faulty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected String limitStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table faulty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected String limitEnd;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table faulty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public FaultyExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table faulty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table faulty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table faulty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table faulty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table faulty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table faulty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table faulty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table faulty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table faulty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table faulty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table faulty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setLimitStart(String limitStart) {
		this.limitStart = limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table faulty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getLimitStart() {
		return limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table faulty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setLimitEnd(String limitEnd) {
		this.limitEnd = limitEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table faulty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getLimitEnd() {
		return limitEnd;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table faulty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("code is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("code is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("code =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("code <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("code >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("code >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("code <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("code <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("code like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("code not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("code in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("code not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("code between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("code not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(String value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(String value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(String value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(String value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(String value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(String value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLike(String value) {
			addCriterion("type like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotLike(String value) {
			addCriterion("type not like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<String> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<String> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(String value1, String value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(String value1, String value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andCreatedByIsNull() {
			addCriterion("created_by is null");
			return (Criteria) this;
		}

		public Criteria andCreatedByIsNotNull() {
			addCriterion("created_by is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedByEqualTo(String value) {
			addCriterion("created_by =", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotEqualTo(String value) {
			addCriterion("created_by <>", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByGreaterThan(String value) {
			addCriterion("created_by >", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
			addCriterion("created_by >=", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByLessThan(String value) {
			addCriterion("created_by <", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByLessThanOrEqualTo(String value) {
			addCriterion("created_by <=", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByLike(String value) {
			addCriterion("created_by like", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotLike(String value) {
			addCriterion("created_by not like", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByIn(List<String> values) {
			addCriterion("created_by in", values, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotIn(List<String> values) {
			addCriterion("created_by not in", values, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByBetween(String value1, String value2) {
			addCriterion("created_by between", value1, value2, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotBetween(String value1, String value2) {
			addCriterion("created_by not between", value1, value2, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatorIsNull() {
			addCriterion("creator is null");
			return (Criteria) this;
		}

		public Criteria andCreatorIsNotNull() {
			addCriterion("creator is not null");
			return (Criteria) this;
		}

		public Criteria andCreatorEqualTo(String value) {
			addCriterion("creator =", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotEqualTo(String value) {
			addCriterion("creator <>", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorGreaterThan(String value) {
			addCriterion("creator >", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorGreaterThanOrEqualTo(String value) {
			addCriterion("creator >=", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLessThan(String value) {
			addCriterion("creator <", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLessThanOrEqualTo(String value) {
			addCriterion("creator <=", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLike(String value) {
			addCriterion("creator like", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotLike(String value) {
			addCriterion("creator not like", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorIn(List<String> values) {
			addCriterion("creator in", values, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotIn(List<String> values) {
			addCriterion("creator not in", values, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorBetween(String value1, String value2) {
			addCriterion("creator between", value1, value2, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotBetween(String value1, String value2) {
			addCriterion("creator not between", value1, value2, "creator");
			return (Criteria) this;
		}

		public Criteria andQtyIsNull() {
			addCriterion("qty is null");
			return (Criteria) this;
		}

		public Criteria andQtyIsNotNull() {
			addCriterion("qty is not null");
			return (Criteria) this;
		}

		public Criteria andQtyEqualTo(Double value) {
			addCriterion("qty =", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyNotEqualTo(Double value) {
			addCriterion("qty <>", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyGreaterThan(Double value) {
			addCriterion("qty >", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyGreaterThanOrEqualTo(Double value) {
			addCriterion("qty >=", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyLessThan(Double value) {
			addCriterion("qty <", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyLessThanOrEqualTo(Double value) {
			addCriterion("qty <=", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyIn(List<Double> values) {
			addCriterion("qty in", values, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyNotIn(List<Double> values) {
			addCriterion("qty not in", values, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyBetween(Double value1, Double value2) {
			addCriterion("qty between", value1, value2, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyNotBetween(Double value1, Double value2) {
			addCriterion("qty not between", value1, value2, "qty");
			return (Criteria) this;
		}

		public Criteria andCreatedOnIsNull() {
			addCriterion("created_on is null");
			return (Criteria) this;
		}

		public Criteria andCreatedOnIsNotNull() {
			addCriterion("created_on is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedOnEqualTo(Date value) {
			addCriterionForJDBCDate("created_on =", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnNotEqualTo(Date value) {
			addCriterionForJDBCDate("created_on <>", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnGreaterThan(Date value) {
			addCriterionForJDBCDate("created_on >", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("created_on >=", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnLessThan(Date value) {
			addCriterionForJDBCDate("created_on <", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("created_on <=", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnIn(List<Date> values) {
			addCriterionForJDBCDate("created_on in", values, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnNotIn(List<Date> values) {
			addCriterionForJDBCDate("created_on not in", values, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("created_on between", value1, value2, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("created_on not between", value1, value2, "createdOn");
			return (Criteria) this;
		}

		public Criteria andReferenceNoIsNull() {
			addCriterion("reference_no is null");
			return (Criteria) this;
		}

		public Criteria andReferenceNoIsNotNull() {
			addCriterion("reference_no is not null");
			return (Criteria) this;
		}

		public Criteria andReferenceNoEqualTo(String value) {
			addCriterion("reference_no =", value, "referenceNo");
			return (Criteria) this;
		}

		public Criteria andReferenceNoNotEqualTo(String value) {
			addCriterion("reference_no <>", value, "referenceNo");
			return (Criteria) this;
		}

		public Criteria andReferenceNoGreaterThan(String value) {
			addCriterion("reference_no >", value, "referenceNo");
			return (Criteria) this;
		}

		public Criteria andReferenceNoGreaterThanOrEqualTo(String value) {
			addCriterion("reference_no >=", value, "referenceNo");
			return (Criteria) this;
		}

		public Criteria andReferenceNoLessThan(String value) {
			addCriterion("reference_no <", value, "referenceNo");
			return (Criteria) this;
		}

		public Criteria andReferenceNoLessThanOrEqualTo(String value) {
			addCriterion("reference_no <=", value, "referenceNo");
			return (Criteria) this;
		}

		public Criteria andReferenceNoLike(String value) {
			addCriterion("reference_no like", value, "referenceNo");
			return (Criteria) this;
		}

		public Criteria andReferenceNoNotLike(String value) {
			addCriterion("reference_no not like", value, "referenceNo");
			return (Criteria) this;
		}

		public Criteria andReferenceNoIn(List<String> values) {
			addCriterion("reference_no in", values, "referenceNo");
			return (Criteria) this;
		}

		public Criteria andReferenceNoNotIn(List<String> values) {
			addCriterion("reference_no not in", values, "referenceNo");
			return (Criteria) this;
		}

		public Criteria andReferenceNoBetween(String value1, String value2) {
			addCriterion("reference_no between", value1, value2, "referenceNo");
			return (Criteria) this;
		}

		public Criteria andReferenceNoNotBetween(String value1, String value2) {
			addCriterion("reference_no not between", value1, value2, "referenceNo");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andApprovalStatusIsNull() {
			addCriterion("approval_status is null");
			return (Criteria) this;
		}

		public Criteria andApprovalStatusIsNotNull() {
			addCriterion("approval_status is not null");
			return (Criteria) this;
		}

		public Criteria andApprovalStatusEqualTo(String value) {
			addCriterion("approval_status =", value, "approvalStatus");
			return (Criteria) this;
		}

		public Criteria andApprovalStatusNotEqualTo(String value) {
			addCriterion("approval_status <>", value, "approvalStatus");
			return (Criteria) this;
		}

		public Criteria andApprovalStatusGreaterThan(String value) {
			addCriterion("approval_status >", value, "approvalStatus");
			return (Criteria) this;
		}

		public Criteria andApprovalStatusGreaterThanOrEqualTo(String value) {
			addCriterion("approval_status >=", value, "approvalStatus");
			return (Criteria) this;
		}

		public Criteria andApprovalStatusLessThan(String value) {
			addCriterion("approval_status <", value, "approvalStatus");
			return (Criteria) this;
		}

		public Criteria andApprovalStatusLessThanOrEqualTo(String value) {
			addCriterion("approval_status <=", value, "approvalStatus");
			return (Criteria) this;
		}

		public Criteria andApprovalStatusLike(String value) {
			addCriterion("approval_status like", value, "approvalStatus");
			return (Criteria) this;
		}

		public Criteria andApprovalStatusNotLike(String value) {
			addCriterion("approval_status not like", value, "approvalStatus");
			return (Criteria) this;
		}

		public Criteria andApprovalStatusIn(List<String> values) {
			addCriterion("approval_status in", values, "approvalStatus");
			return (Criteria) this;
		}

		public Criteria andApprovalStatusNotIn(List<String> values) {
			addCriterion("approval_status not in", values, "approvalStatus");
			return (Criteria) this;
		}

		public Criteria andApprovalStatusBetween(String value1, String value2) {
			addCriterion("approval_status between", value1, value2, "approvalStatus");
			return (Criteria) this;
		}

		public Criteria andApprovalStatusNotBetween(String value1, String value2) {
			addCriterion("approval_status not between", value1, value2, "approvalStatus");
			return (Criteria) this;
		}

		public Criteria andPmcStatusIsNull() {
			addCriterion("pmc_status is null");
			return (Criteria) this;
		}

		public Criteria andPmcStatusIsNotNull() {
			addCriterion("pmc_status is not null");
			return (Criteria) this;
		}

		public Criteria andPmcStatusEqualTo(String value) {
			addCriterion("pmc_status =", value, "pmcStatus");
			return (Criteria) this;
		}

		public Criteria andPmcStatusNotEqualTo(String value) {
			addCriterion("pmc_status <>", value, "pmcStatus");
			return (Criteria) this;
		}

		public Criteria andPmcStatusGreaterThan(String value) {
			addCriterion("pmc_status >", value, "pmcStatus");
			return (Criteria) this;
		}

		public Criteria andPmcStatusGreaterThanOrEqualTo(String value) {
			addCriterion("pmc_status >=", value, "pmcStatus");
			return (Criteria) this;
		}

		public Criteria andPmcStatusLessThan(String value) {
			addCriterion("pmc_status <", value, "pmcStatus");
			return (Criteria) this;
		}

		public Criteria andPmcStatusLessThanOrEqualTo(String value) {
			addCriterion("pmc_status <=", value, "pmcStatus");
			return (Criteria) this;
		}

		public Criteria andPmcStatusLike(String value) {
			addCriterion("pmc_status like", value, "pmcStatus");
			return (Criteria) this;
		}

		public Criteria andPmcStatusNotLike(String value) {
			addCriterion("pmc_status not like", value, "pmcStatus");
			return (Criteria) this;
		}

		public Criteria andPmcStatusIn(List<String> values) {
			addCriterion("pmc_status in", values, "pmcStatus");
			return (Criteria) this;
		}

		public Criteria andPmcStatusNotIn(List<String> values) {
			addCriterion("pmc_status not in", values, "pmcStatus");
			return (Criteria) this;
		}

		public Criteria andPmcStatusBetween(String value1, String value2) {
			addCriterion("pmc_status between", value1, value2, "pmcStatus");
			return (Criteria) this;
		}

		public Criteria andPmcStatusNotBetween(String value1, String value2) {
			addCriterion("pmc_status not between", value1, value2, "pmcStatus");
			return (Criteria) this;
		}

		public Criteria andDApproverIdIsNull() {
			addCriterion("d_approver_id is null");
			return (Criteria) this;
		}

		public Criteria andDApproverIdIsNotNull() {
			addCriterion("d_approver_id is not null");
			return (Criteria) this;
		}

		public Criteria andDApproverIdEqualTo(String value) {
			addCriterion("d_approver_id =", value, "dApproverId");
			return (Criteria) this;
		}

		public Criteria andDApproverIdNotEqualTo(String value) {
			addCriterion("d_approver_id <>", value, "dApproverId");
			return (Criteria) this;
		}

		public Criteria andDApproverIdGreaterThan(String value) {
			addCriterion("d_approver_id >", value, "dApproverId");
			return (Criteria) this;
		}

		public Criteria andDApproverIdGreaterThanOrEqualTo(String value) {
			addCriterion("d_approver_id >=", value, "dApproverId");
			return (Criteria) this;
		}

		public Criteria andDApproverIdLessThan(String value) {
			addCriterion("d_approver_id <", value, "dApproverId");
			return (Criteria) this;
		}

		public Criteria andDApproverIdLessThanOrEqualTo(String value) {
			addCriterion("d_approver_id <=", value, "dApproverId");
			return (Criteria) this;
		}

		public Criteria andDApproverIdLike(String value) {
			addCriterion("d_approver_id like", value, "dApproverId");
			return (Criteria) this;
		}

		public Criteria andDApproverIdNotLike(String value) {
			addCriterion("d_approver_id not like", value, "dApproverId");
			return (Criteria) this;
		}

		public Criteria andDApproverIdIn(List<String> values) {
			addCriterion("d_approver_id in", values, "dApproverId");
			return (Criteria) this;
		}

		public Criteria andDApproverIdNotIn(List<String> values) {
			addCriterion("d_approver_id not in", values, "dApproverId");
			return (Criteria) this;
		}

		public Criteria andDApproverIdBetween(String value1, String value2) {
			addCriterion("d_approver_id between", value1, value2, "dApproverId");
			return (Criteria) this;
		}

		public Criteria andDApproverIdNotBetween(String value1, String value2) {
			addCriterion("d_approver_id not between", value1, value2, "dApproverId");
			return (Criteria) this;
		}

		public Criteria andDApproverIsNull() {
			addCriterion("d_approver is null");
			return (Criteria) this;
		}

		public Criteria andDApproverIsNotNull() {
			addCriterion("d_approver is not null");
			return (Criteria) this;
		}

		public Criteria andDApproverEqualTo(String value) {
			addCriterion("d_approver =", value, "dApprover");
			return (Criteria) this;
		}

		public Criteria andDApproverNotEqualTo(String value) {
			addCriterion("d_approver <>", value, "dApprover");
			return (Criteria) this;
		}

		public Criteria andDApproverGreaterThan(String value) {
			addCriterion("d_approver >", value, "dApprover");
			return (Criteria) this;
		}

		public Criteria andDApproverGreaterThanOrEqualTo(String value) {
			addCriterion("d_approver >=", value, "dApprover");
			return (Criteria) this;
		}

		public Criteria andDApproverLessThan(String value) {
			addCriterion("d_approver <", value, "dApprover");
			return (Criteria) this;
		}

		public Criteria andDApproverLessThanOrEqualTo(String value) {
			addCriterion("d_approver <=", value, "dApprover");
			return (Criteria) this;
		}

		public Criteria andDApproverLike(String value) {
			addCriterion("d_approver like", value, "dApprover");
			return (Criteria) this;
		}

		public Criteria andDApproverNotLike(String value) {
			addCriterion("d_approver not like", value, "dApprover");
			return (Criteria) this;
		}

		public Criteria andDApproverIn(List<String> values) {
			addCriterion("d_approver in", values, "dApprover");
			return (Criteria) this;
		}

		public Criteria andDApproverNotIn(List<String> values) {
			addCriterion("d_approver not in", values, "dApprover");
			return (Criteria) this;
		}

		public Criteria andDApproverBetween(String value1, String value2) {
			addCriterion("d_approver between", value1, value2, "dApprover");
			return (Criteria) this;
		}

		public Criteria andDApproverNotBetween(String value1, String value2) {
			addCriterion("d_approver not between", value1, value2, "dApprover");
			return (Criteria) this;
		}

		public Criteria andDApprovalStatusIsNull() {
			addCriterion("d_approval_status is null");
			return (Criteria) this;
		}

		public Criteria andDApprovalStatusIsNotNull() {
			addCriterion("d_approval_status is not null");
			return (Criteria) this;
		}

		public Criteria andDApprovalStatusEqualTo(String value) {
			addCriterion("d_approval_status =", value, "dApprovalStatus");
			return (Criteria) this;
		}

		public Criteria andDApprovalStatusNotEqualTo(String value) {
			addCriterion("d_approval_status <>", value, "dApprovalStatus");
			return (Criteria) this;
		}

		public Criteria andDApprovalStatusGreaterThan(String value) {
			addCriterion("d_approval_status >", value, "dApprovalStatus");
			return (Criteria) this;
		}

		public Criteria andDApprovalStatusGreaterThanOrEqualTo(String value) {
			addCriterion("d_approval_status >=", value, "dApprovalStatus");
			return (Criteria) this;
		}

		public Criteria andDApprovalStatusLessThan(String value) {
			addCriterion("d_approval_status <", value, "dApprovalStatus");
			return (Criteria) this;
		}

		public Criteria andDApprovalStatusLessThanOrEqualTo(String value) {
			addCriterion("d_approval_status <=", value, "dApprovalStatus");
			return (Criteria) this;
		}

		public Criteria andDApprovalStatusLike(String value) {
			addCriterion("d_approval_status like", value, "dApprovalStatus");
			return (Criteria) this;
		}

		public Criteria andDApprovalStatusNotLike(String value) {
			addCriterion("d_approval_status not like", value, "dApprovalStatus");
			return (Criteria) this;
		}

		public Criteria andDApprovalStatusIn(List<String> values) {
			addCriterion("d_approval_status in", values, "dApprovalStatus");
			return (Criteria) this;
		}

		public Criteria andDApprovalStatusNotIn(List<String> values) {
			addCriterion("d_approval_status not in", values, "dApprovalStatus");
			return (Criteria) this;
		}

		public Criteria andDApprovalStatusBetween(String value1, String value2) {
			addCriterion("d_approval_status between", value1, value2, "dApprovalStatus");
			return (Criteria) this;
		}

		public Criteria andDApprovalStatusNotBetween(String value1, String value2) {
			addCriterion("d_approval_status not between", value1, value2, "dApprovalStatus");
			return (Criteria) this;
		}

		public Criteria andSupplierIdIsNull() {
			addCriterion("supplier_id is null");
			return (Criteria) this;
		}

		public Criteria andSupplierIdIsNotNull() {
			addCriterion("supplier_id is not null");
			return (Criteria) this;
		}

		public Criteria andSupplierIdEqualTo(String value) {
			addCriterion("supplier_id =", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdNotEqualTo(String value) {
			addCriterion("supplier_id <>", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdGreaterThan(String value) {
			addCriterion("supplier_id >", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdGreaterThanOrEqualTo(String value) {
			addCriterion("supplier_id >=", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdLessThan(String value) {
			addCriterion("supplier_id <", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdLessThanOrEqualTo(String value) {
			addCriterion("supplier_id <=", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdLike(String value) {
			addCriterion("supplier_id like", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdNotLike(String value) {
			addCriterion("supplier_id not like", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdIn(List<String> values) {
			addCriterion("supplier_id in", values, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdNotIn(List<String> values) {
			addCriterion("supplier_id not in", values, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdBetween(String value1, String value2) {
			addCriterion("supplier_id between", value1, value2, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdNotBetween(String value1, String value2) {
			addCriterion("supplier_id not between", value1, value2, "supplierId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table faulty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table faulty
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 19 00:03:40 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}