package com.wecloud.erp.model;

import java.util.Date;

public class Inventory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inventory.ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inventory.created_by
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inventory.CREATED_ON
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Date createdOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inventory.UPDATED_ON
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Date updatedOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inventory.STORAGE_ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String storageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inventory.SYSTEM_QTY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Double systemQty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inventory.QTY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Double qty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inventory.BALANCE
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Double balance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inventory.STATUS
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Integer status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inventory.ID
	 * @return  the value of inventory.ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inventory.ID
	 * @param id  the value for inventory.ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inventory.created_by
	 * @return  the value of inventory.created_by
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inventory.created_by
	 * @param createdBy  the value for inventory.created_by
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy == null ? null : createdBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inventory.CREATED_ON
	 * @return  the value of inventory.CREATED_ON
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Date getCreatedOn() {
		return createdOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inventory.CREATED_ON
	 * @param createdOn  the value for inventory.CREATED_ON
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inventory.UPDATED_ON
	 * @return  the value of inventory.UPDATED_ON
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Date getUpdatedOn() {
		return updatedOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inventory.UPDATED_ON
	 * @param updatedOn  the value for inventory.UPDATED_ON
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inventory.STORAGE_ID
	 * @return  the value of inventory.STORAGE_ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getStorageId() {
		return storageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inventory.STORAGE_ID
	 * @param storageId  the value for inventory.STORAGE_ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setStorageId(String storageId) {
		this.storageId = storageId == null ? null : storageId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inventory.SYSTEM_QTY
	 * @return  the value of inventory.SYSTEM_QTY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Double getSystemQty() {
		return systemQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inventory.SYSTEM_QTY
	 * @param systemQty  the value for inventory.SYSTEM_QTY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setSystemQty(Double systemQty) {
		this.systemQty = systemQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inventory.QTY
	 * @return  the value of inventory.QTY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Double getQty() {
		return qty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inventory.QTY
	 * @param qty  the value for inventory.QTY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setQty(Double qty) {
		this.qty = qty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inventory.BALANCE
	 * @return  the value of inventory.BALANCE
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Double getBalance() {
		return balance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inventory.BALANCE
	 * @param balance  the value for inventory.BALANCE
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setBalance(Double balance) {
		this.balance = balance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inventory.STATUS
	 * @return  the value of inventory.STATUS
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inventory.STATUS
	 * @param status  the value for inventory.STATUS
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
}