package com.wecloud.erp.model;

public class PoItem {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column poitem.id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column poitem.order_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column poitem.item_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String itemId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column poitem.name
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column poitem.code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column poitem.style
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String style;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column poitem.qty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Double qty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column poitem.uom
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String uom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column poitem.unit_price
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Double unitPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column poitem.total_amount
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Double totalAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column poitem.instock_qty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Double instockQty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column poitem.description
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column poitem.id
	 * @return  the value of poitem.id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column poitem.id
	 * @param id  the value for poitem.id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column poitem.order_id
	 * @return  the value of poitem.order_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column poitem.order_id
	 * @param orderId  the value for poitem.order_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId == null ? null : orderId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column poitem.item_id
	 * @return  the value of poitem.item_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getItemId() {
		return itemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column poitem.item_id
	 * @param itemId  the value for poitem.item_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setItemId(String itemId) {
		this.itemId = itemId == null ? null : itemId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column poitem.name
	 * @return  the value of poitem.name
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column poitem.name
	 * @param name  the value for poitem.name
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column poitem.code
	 * @return  the value of poitem.code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column poitem.code
	 * @param code  the value for poitem.code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column poitem.style
	 * @return  the value of poitem.style
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getStyle() {
		return style;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column poitem.style
	 * @param style  the value for poitem.style
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setStyle(String style) {
		this.style = style == null ? null : style.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column poitem.qty
	 * @return  the value of poitem.qty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Double getQty() {
		return qty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column poitem.qty
	 * @param qty  the value for poitem.qty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setQty(Double qty) {
		this.qty = qty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column poitem.uom
	 * @return  the value of poitem.uom
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getUom() {
		return uom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column poitem.uom
	 * @param uom  the value for poitem.uom
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setUom(String uom) {
		this.uom = uom == null ? null : uom.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column poitem.unit_price
	 * @return  the value of poitem.unit_price
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Double getUnitPrice() {
		return unitPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column poitem.unit_price
	 * @param unitPrice  the value for poitem.unit_price
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setUnitPrice(Double unitPrice) {
		this.unitPrice = unitPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column poitem.total_amount
	 * @return  the value of poitem.total_amount
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Double getTotalAmount() {
		return totalAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column poitem.total_amount
	 * @param totalAmount  the value for poitem.total_amount
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setTotalAmount(Double totalAmount) {
		this.totalAmount = totalAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column poitem.instock_qty
	 * @return  the value of poitem.instock_qty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Double getInstockQty() {
		return instockQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column poitem.instock_qty
	 * @param instockQty  the value for poitem.instock_qty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setInstockQty(Double instockQty) {
		this.instockQty = instockQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column poitem.description
	 * @return  the value of poitem.description
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column poitem.description
	 * @param description  the value for poitem.description
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}
}