package com.wecloud.erp.model;

public class PoReturnItem {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column poreturnitem.id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column poreturnitem.return_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String returnId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column poreturnitem.item_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String itemId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column poreturnitem.qty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Double qty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column poreturnitem.uom
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String uom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column poreturnitem.description
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column poreturnitem.id
	 * @return  the value of poreturnitem.id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column poreturnitem.id
	 * @param id  the value for poreturnitem.id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column poreturnitem.return_id
	 * @return  the value of poreturnitem.return_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getReturnId() {
		return returnId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column poreturnitem.return_id
	 * @param returnId  the value for poreturnitem.return_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setReturnId(String returnId) {
		this.returnId = returnId == null ? null : returnId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column poreturnitem.item_id
	 * @return  the value of poreturnitem.item_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getItemId() {
		return itemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column poreturnitem.item_id
	 * @param itemId  the value for poreturnitem.item_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setItemId(String itemId) {
		this.itemId = itemId == null ? null : itemId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column poreturnitem.qty
	 * @return  the value of poreturnitem.qty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Double getQty() {
		return qty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column poreturnitem.qty
	 * @param qty  the value for poreturnitem.qty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setQty(Double qty) {
		this.qty = qty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column poreturnitem.uom
	 * @return  the value of poreturnitem.uom
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getUom() {
		return uom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column poreturnitem.uom
	 * @param uom  the value for poreturnitem.uom
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setUom(String uom) {
		this.uom = uom == null ? null : uom.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column poreturnitem.description
	 * @return  the value of poreturnitem.description
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column poreturnitem.description
	 * @param description  the value for poreturnitem.description
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}
}