package com.wecloud.erp.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class PoSummaryExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected String limitStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected String limitEnd;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public PoSummaryExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setLimitStart(String limitStart) {
		this.limitStart = limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getLimitStart() {
		return limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setLimitEnd(String limitEnd) {
		this.limitEnd = limitEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getLimitEnd() {
		return limitEnd;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCreatedOnIsNull() {
			addCriterion("created_on is null");
			return (Criteria) this;
		}

		public Criteria andCreatedOnIsNotNull() {
			addCriterion("created_on is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedOnEqualTo(Date value) {
			addCriterionForJDBCDate("created_on =", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnNotEqualTo(Date value) {
			addCriterionForJDBCDate("created_on <>", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnGreaterThan(Date value) {
			addCriterionForJDBCDate("created_on >", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("created_on >=", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnLessThan(Date value) {
			addCriterionForJDBCDate("created_on <", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("created_on <=", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnIn(List<Date> values) {
			addCriterionForJDBCDate("created_on in", values, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnNotIn(List<Date> values) {
			addCriterionForJDBCDate("created_on not in", values, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("created_on between", value1, value2, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("created_on not between", value1, value2, "createdOn");
			return (Criteria) this;
		}

		public Criteria andSupplierIdIsNull() {
			addCriterion("supplier_id is null");
			return (Criteria) this;
		}

		public Criteria andSupplierIdIsNotNull() {
			addCriterion("supplier_id is not null");
			return (Criteria) this;
		}

		public Criteria andSupplierIdEqualTo(String value) {
			addCriterion("supplier_id =", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdNotEqualTo(String value) {
			addCriterion("supplier_id <>", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdGreaterThan(String value) {
			addCriterion("supplier_id >", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdGreaterThanOrEqualTo(String value) {
			addCriterion("supplier_id >=", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdLessThan(String value) {
			addCriterion("supplier_id <", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdLessThanOrEqualTo(String value) {
			addCriterion("supplier_id <=", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdLike(String value) {
			addCriterion("supplier_id like", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdNotLike(String value) {
			addCriterion("supplier_id not like", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdIn(List<String> values) {
			addCriterion("supplier_id in", values, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdNotIn(List<String> values) {
			addCriterion("supplier_id not in", values, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdBetween(String value1, String value2) {
			addCriterion("supplier_id between", value1, value2, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdNotBetween(String value1, String value2) {
			addCriterion("supplier_id not between", value1, value2, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierNameIsNull() {
			addCriterion("supplier_name is null");
			return (Criteria) this;
		}

		public Criteria andSupplierNameIsNotNull() {
			addCriterion("supplier_name is not null");
			return (Criteria) this;
		}

		public Criteria andSupplierNameEqualTo(String value) {
			addCriterion("supplier_name =", value, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameNotEqualTo(String value) {
			addCriterion("supplier_name <>", value, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameGreaterThan(String value) {
			addCriterion("supplier_name >", value, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameGreaterThanOrEqualTo(String value) {
			addCriterion("supplier_name >=", value, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameLessThan(String value) {
			addCriterion("supplier_name <", value, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameLessThanOrEqualTo(String value) {
			addCriterion("supplier_name <=", value, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameLike(String value) {
			addCriterion("supplier_name like", value, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameNotLike(String value) {
			addCriterion("supplier_name not like", value, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameIn(List<String> values) {
			addCriterion("supplier_name in", values, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameNotIn(List<String> values) {
			addCriterion("supplier_name not in", values, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameBetween(String value1, String value2) {
			addCriterion("supplier_name between", value1, value2, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameNotBetween(String value1, String value2) {
			addCriterion("supplier_name not between", value1, value2, "supplierName");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(String value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(String value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(String value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(String value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(String value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(String value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLike(String value) {
			addCriterion("type like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotLike(String value) {
			addCriterion("type not like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<String> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<String> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(String value1, String value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(String value1, String value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("code is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("code is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("code =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("code <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("code >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("code >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("code <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("code <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("code like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("code not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("code in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("code not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("code between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("code not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andStyleIsNull() {
			addCriterion("style is null");
			return (Criteria) this;
		}

		public Criteria andStyleIsNotNull() {
			addCriterion("style is not null");
			return (Criteria) this;
		}

		public Criteria andStyleEqualTo(String value) {
			addCriterion("style =", value, "style");
			return (Criteria) this;
		}

		public Criteria andStyleNotEqualTo(String value) {
			addCriterion("style <>", value, "style");
			return (Criteria) this;
		}

		public Criteria andStyleGreaterThan(String value) {
			addCriterion("style >", value, "style");
			return (Criteria) this;
		}

		public Criteria andStyleGreaterThanOrEqualTo(String value) {
			addCriterion("style >=", value, "style");
			return (Criteria) this;
		}

		public Criteria andStyleLessThan(String value) {
			addCriterion("style <", value, "style");
			return (Criteria) this;
		}

		public Criteria andStyleLessThanOrEqualTo(String value) {
			addCriterion("style <=", value, "style");
			return (Criteria) this;
		}

		public Criteria andStyleLike(String value) {
			addCriterion("style like", value, "style");
			return (Criteria) this;
		}

		public Criteria andStyleNotLike(String value) {
			addCriterion("style not like", value, "style");
			return (Criteria) this;
		}

		public Criteria andStyleIn(List<String> values) {
			addCriterion("style in", values, "style");
			return (Criteria) this;
		}

		public Criteria andStyleNotIn(List<String> values) {
			addCriterion("style not in", values, "style");
			return (Criteria) this;
		}

		public Criteria andStyleBetween(String value1, String value2) {
			addCriterion("style between", value1, value2, "style");
			return (Criteria) this;
		}

		public Criteria andStyleNotBetween(String value1, String value2) {
			addCriterion("style not between", value1, value2, "style");
			return (Criteria) this;
		}

		public Criteria andQtyIsNull() {
			addCriterion("qty is null");
			return (Criteria) this;
		}

		public Criteria andQtyIsNotNull() {
			addCriterion("qty is not null");
			return (Criteria) this;
		}

		public Criteria andQtyEqualTo(Double value) {
			addCriterion("qty =", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyNotEqualTo(Double value) {
			addCriterion("qty <>", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyGreaterThan(Double value) {
			addCriterion("qty >", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyGreaterThanOrEqualTo(Double value) {
			addCriterion("qty >=", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyLessThan(Double value) {
			addCriterion("qty <", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyLessThanOrEqualTo(Double value) {
			addCriterion("qty <=", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyIn(List<Double> values) {
			addCriterion("qty in", values, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyNotIn(List<Double> values) {
			addCriterion("qty not in", values, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyBetween(Double value1, Double value2) {
			addCriterion("qty between", value1, value2, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyNotBetween(Double value1, Double value2) {
			addCriterion("qty not between", value1, value2, "qty");
			return (Criteria) this;
		}

		public Criteria andUomIsNull() {
			addCriterion("uom is null");
			return (Criteria) this;
		}

		public Criteria andUomIsNotNull() {
			addCriterion("uom is not null");
			return (Criteria) this;
		}

		public Criteria andUomEqualTo(String value) {
			addCriterion("uom =", value, "uom");
			return (Criteria) this;
		}

		public Criteria andUomNotEqualTo(String value) {
			addCriterion("uom <>", value, "uom");
			return (Criteria) this;
		}

		public Criteria andUomGreaterThan(String value) {
			addCriterion("uom >", value, "uom");
			return (Criteria) this;
		}

		public Criteria andUomGreaterThanOrEqualTo(String value) {
			addCriterion("uom >=", value, "uom");
			return (Criteria) this;
		}

		public Criteria andUomLessThan(String value) {
			addCriterion("uom <", value, "uom");
			return (Criteria) this;
		}

		public Criteria andUomLessThanOrEqualTo(String value) {
			addCriterion("uom <=", value, "uom");
			return (Criteria) this;
		}

		public Criteria andUomLike(String value) {
			addCriterion("uom like", value, "uom");
			return (Criteria) this;
		}

		public Criteria andUomNotLike(String value) {
			addCriterion("uom not like", value, "uom");
			return (Criteria) this;
		}

		public Criteria andUomIn(List<String> values) {
			addCriterion("uom in", values, "uom");
			return (Criteria) this;
		}

		public Criteria andUomNotIn(List<String> values) {
			addCriterion("uom not in", values, "uom");
			return (Criteria) this;
		}

		public Criteria andUomBetween(String value1, String value2) {
			addCriterion("uom between", value1, value2, "uom");
			return (Criteria) this;
		}

		public Criteria andUomNotBetween(String value1, String value2) {
			addCriterion("uom not between", value1, value2, "uom");
			return (Criteria) this;
		}

		public Criteria andUnitPriceIsNull() {
			addCriterion("unit_price is null");
			return (Criteria) this;
		}

		public Criteria andUnitPriceIsNotNull() {
			addCriterion("unit_price is not null");
			return (Criteria) this;
		}

		public Criteria andUnitPriceEqualTo(Double value) {
			addCriterion("unit_price =", value, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceNotEqualTo(Double value) {
			addCriterion("unit_price <>", value, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceGreaterThan(Double value) {
			addCriterion("unit_price >", value, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceGreaterThanOrEqualTo(Double value) {
			addCriterion("unit_price >=", value, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceLessThan(Double value) {
			addCriterion("unit_price <", value, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceLessThanOrEqualTo(Double value) {
			addCriterion("unit_price <=", value, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceIn(List<Double> values) {
			addCriterion("unit_price in", values, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceNotIn(List<Double> values) {
			addCriterion("unit_price not in", values, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceBetween(Double value1, Double value2) {
			addCriterion("unit_price between", value1, value2, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceNotBetween(Double value1, Double value2) {
			addCriterion("unit_price not between", value1, value2, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andAmountIsNull() {
			addCriterion("amount is null");
			return (Criteria) this;
		}

		public Criteria andAmountIsNotNull() {
			addCriterion("amount is not null");
			return (Criteria) this;
		}

		public Criteria andAmountEqualTo(Double value) {
			addCriterion("amount =", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotEqualTo(Double value) {
			addCriterion("amount <>", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThan(Double value) {
			addCriterion("amount >", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThanOrEqualTo(Double value) {
			addCriterion("amount >=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThan(Double value) {
			addCriterion("amount <", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThanOrEqualTo(Double value) {
			addCriterion("amount <=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountIn(List<Double> values) {
			addCriterion("amount in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotIn(List<Double> values) {
			addCriterion("amount not in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountBetween(Double value1, Double value2) {
			addCriterion("amount between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotBetween(Double value1, Double value2) {
			addCriterion("amount not between", value1, value2, "amount");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table posummary
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 19 00:03:40 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}