package com.wecloud.erp.model;

import java.util.Date;

public class ProduceRequestView {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producerequestview.id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producerequestview.so_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String soId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producerequestview.notice_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String noticeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producerequestview.req_code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String reqCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producerequestview.delivery_date
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Date deliveryDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producerequestview.pmc_status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String pmcStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producerequestview.qty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Double qty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producerequestview.created_on
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Date createdOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producerequestview.code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producerequestview.creator
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String creator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producerequestview.description
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producerequestview.id
	 * @return  the value of producerequestview.id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producerequestview.id
	 * @param id  the value for producerequestview.id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producerequestview.so_id
	 * @return  the value of producerequestview.so_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getSoId() {
		return soId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producerequestview.so_id
	 * @param soId  the value for producerequestview.so_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setSoId(String soId) {
		this.soId = soId == null ? null : soId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producerequestview.notice_id
	 * @return  the value of producerequestview.notice_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getNoticeId() {
		return noticeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producerequestview.notice_id
	 * @param noticeId  the value for producerequestview.notice_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setNoticeId(String noticeId) {
		this.noticeId = noticeId == null ? null : noticeId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producerequestview.req_code
	 * @return  the value of producerequestview.req_code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getReqCode() {
		return reqCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producerequestview.req_code
	 * @param reqCode  the value for producerequestview.req_code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setReqCode(String reqCode) {
		this.reqCode = reqCode == null ? null : reqCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producerequestview.delivery_date
	 * @return  the value of producerequestview.delivery_date
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Date getDeliveryDate() {
		return deliveryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producerequestview.delivery_date
	 * @param deliveryDate  the value for producerequestview.delivery_date
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setDeliveryDate(Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producerequestview.pmc_status
	 * @return  the value of producerequestview.pmc_status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getPmcStatus() {
		return pmcStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producerequestview.pmc_status
	 * @param pmcStatus  the value for producerequestview.pmc_status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setPmcStatus(String pmcStatus) {
		this.pmcStatus = pmcStatus == null ? null : pmcStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producerequestview.qty
	 * @return  the value of producerequestview.qty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Double getQty() {
		return qty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producerequestview.qty
	 * @param qty  the value for producerequestview.qty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setQty(Double qty) {
		this.qty = qty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producerequestview.created_on
	 * @return  the value of producerequestview.created_on
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Date getCreatedOn() {
		return createdOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producerequestview.created_on
	 * @param createdOn  the value for producerequestview.created_on
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producerequestview.code
	 * @return  the value of producerequestview.code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producerequestview.code
	 * @param code  the value for producerequestview.code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producerequestview.creator
	 * @return  the value of producerequestview.creator
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producerequestview.creator
	 * @param creator  the value for producerequestview.creator
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCreator(String creator) {
		this.creator = creator == null ? null : creator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producerequestview.description
	 * @return  the value of producerequestview.description
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producerequestview.description
	 * @param description  the value for producerequestview.description
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}
}