package com.wecloud.erp.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProduceRequestViewExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table producerequestview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table producerequestview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table producerequestview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table producerequestview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected String limitStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table producerequestview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected String limitEnd;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producerequestview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public ProduceRequestViewExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producerequestview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producerequestview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producerequestview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producerequestview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producerequestview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producerequestview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producerequestview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producerequestview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producerequestview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producerequestview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producerequestview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setLimitStart(String limitStart) {
		this.limitStart = limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producerequestview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getLimitStart() {
		return limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producerequestview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setLimitEnd(String limitEnd) {
		this.limitEnd = limitEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producerequestview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getLimitEnd() {
		return limitEnd;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table producerequestview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andSoIdIsNull() {
			addCriterion("so_id is null");
			return (Criteria) this;
		}

		public Criteria andSoIdIsNotNull() {
			addCriterion("so_id is not null");
			return (Criteria) this;
		}

		public Criteria andSoIdEqualTo(String value) {
			addCriterion("so_id =", value, "soId");
			return (Criteria) this;
		}

		public Criteria andSoIdNotEqualTo(String value) {
			addCriterion("so_id <>", value, "soId");
			return (Criteria) this;
		}

		public Criteria andSoIdGreaterThan(String value) {
			addCriterion("so_id >", value, "soId");
			return (Criteria) this;
		}

		public Criteria andSoIdGreaterThanOrEqualTo(String value) {
			addCriterion("so_id >=", value, "soId");
			return (Criteria) this;
		}

		public Criteria andSoIdLessThan(String value) {
			addCriterion("so_id <", value, "soId");
			return (Criteria) this;
		}

		public Criteria andSoIdLessThanOrEqualTo(String value) {
			addCriterion("so_id <=", value, "soId");
			return (Criteria) this;
		}

		public Criteria andSoIdLike(String value) {
			addCriterion("so_id like", value, "soId");
			return (Criteria) this;
		}

		public Criteria andSoIdNotLike(String value) {
			addCriterion("so_id not like", value, "soId");
			return (Criteria) this;
		}

		public Criteria andSoIdIn(List<String> values) {
			addCriterion("so_id in", values, "soId");
			return (Criteria) this;
		}

		public Criteria andSoIdNotIn(List<String> values) {
			addCriterion("so_id not in", values, "soId");
			return (Criteria) this;
		}

		public Criteria andSoIdBetween(String value1, String value2) {
			addCriterion("so_id between", value1, value2, "soId");
			return (Criteria) this;
		}

		public Criteria andSoIdNotBetween(String value1, String value2) {
			addCriterion("so_id not between", value1, value2, "soId");
			return (Criteria) this;
		}

		public Criteria andNoticeIdIsNull() {
			addCriterion("notice_id is null");
			return (Criteria) this;
		}

		public Criteria andNoticeIdIsNotNull() {
			addCriterion("notice_id is not null");
			return (Criteria) this;
		}

		public Criteria andNoticeIdEqualTo(String value) {
			addCriterion("notice_id =", value, "noticeId");
			return (Criteria) this;
		}

		public Criteria andNoticeIdNotEqualTo(String value) {
			addCriterion("notice_id <>", value, "noticeId");
			return (Criteria) this;
		}

		public Criteria andNoticeIdGreaterThan(String value) {
			addCriterion("notice_id >", value, "noticeId");
			return (Criteria) this;
		}

		public Criteria andNoticeIdGreaterThanOrEqualTo(String value) {
			addCriterion("notice_id >=", value, "noticeId");
			return (Criteria) this;
		}

		public Criteria andNoticeIdLessThan(String value) {
			addCriterion("notice_id <", value, "noticeId");
			return (Criteria) this;
		}

		public Criteria andNoticeIdLessThanOrEqualTo(String value) {
			addCriterion("notice_id <=", value, "noticeId");
			return (Criteria) this;
		}

		public Criteria andNoticeIdLike(String value) {
			addCriterion("notice_id like", value, "noticeId");
			return (Criteria) this;
		}

		public Criteria andNoticeIdNotLike(String value) {
			addCriterion("notice_id not like", value, "noticeId");
			return (Criteria) this;
		}

		public Criteria andNoticeIdIn(List<String> values) {
			addCriterion("notice_id in", values, "noticeId");
			return (Criteria) this;
		}

		public Criteria andNoticeIdNotIn(List<String> values) {
			addCriterion("notice_id not in", values, "noticeId");
			return (Criteria) this;
		}

		public Criteria andNoticeIdBetween(String value1, String value2) {
			addCriterion("notice_id between", value1, value2, "noticeId");
			return (Criteria) this;
		}

		public Criteria andNoticeIdNotBetween(String value1, String value2) {
			addCriterion("notice_id not between", value1, value2, "noticeId");
			return (Criteria) this;
		}

		public Criteria andReqCodeIsNull() {
			addCriterion("req_code is null");
			return (Criteria) this;
		}

		public Criteria andReqCodeIsNotNull() {
			addCriterion("req_code is not null");
			return (Criteria) this;
		}

		public Criteria andReqCodeEqualTo(String value) {
			addCriterion("req_code =", value, "reqCode");
			return (Criteria) this;
		}

		public Criteria andReqCodeNotEqualTo(String value) {
			addCriterion("req_code <>", value, "reqCode");
			return (Criteria) this;
		}

		public Criteria andReqCodeGreaterThan(String value) {
			addCriterion("req_code >", value, "reqCode");
			return (Criteria) this;
		}

		public Criteria andReqCodeGreaterThanOrEqualTo(String value) {
			addCriterion("req_code >=", value, "reqCode");
			return (Criteria) this;
		}

		public Criteria andReqCodeLessThan(String value) {
			addCriterion("req_code <", value, "reqCode");
			return (Criteria) this;
		}

		public Criteria andReqCodeLessThanOrEqualTo(String value) {
			addCriterion("req_code <=", value, "reqCode");
			return (Criteria) this;
		}

		public Criteria andReqCodeLike(String value) {
			addCriterion("req_code like", value, "reqCode");
			return (Criteria) this;
		}

		public Criteria andReqCodeNotLike(String value) {
			addCriterion("req_code not like", value, "reqCode");
			return (Criteria) this;
		}

		public Criteria andReqCodeIn(List<String> values) {
			addCriterion("req_code in", values, "reqCode");
			return (Criteria) this;
		}

		public Criteria andReqCodeNotIn(List<String> values) {
			addCriterion("req_code not in", values, "reqCode");
			return (Criteria) this;
		}

		public Criteria andReqCodeBetween(String value1, String value2) {
			addCriterion("req_code between", value1, value2, "reqCode");
			return (Criteria) this;
		}

		public Criteria andReqCodeNotBetween(String value1, String value2) {
			addCriterion("req_code not between", value1, value2, "reqCode");
			return (Criteria) this;
		}

		public Criteria andDeliveryDateIsNull() {
			addCriterion("delivery_date is null");
			return (Criteria) this;
		}

		public Criteria andDeliveryDateIsNotNull() {
			addCriterion("delivery_date is not null");
			return (Criteria) this;
		}

		public Criteria andDeliveryDateEqualTo(Date value) {
			addCriterion("delivery_date =", value, "deliveryDate");
			return (Criteria) this;
		}

		public Criteria andDeliveryDateNotEqualTo(Date value) {
			addCriterion("delivery_date <>", value, "deliveryDate");
			return (Criteria) this;
		}

		public Criteria andDeliveryDateGreaterThan(Date value) {
			addCriterion("delivery_date >", value, "deliveryDate");
			return (Criteria) this;
		}

		public Criteria andDeliveryDateGreaterThanOrEqualTo(Date value) {
			addCriterion("delivery_date >=", value, "deliveryDate");
			return (Criteria) this;
		}

		public Criteria andDeliveryDateLessThan(Date value) {
			addCriterion("delivery_date <", value, "deliveryDate");
			return (Criteria) this;
		}

		public Criteria andDeliveryDateLessThanOrEqualTo(Date value) {
			addCriterion("delivery_date <=", value, "deliveryDate");
			return (Criteria) this;
		}

		public Criteria andDeliveryDateIn(List<Date> values) {
			addCriterion("delivery_date in", values, "deliveryDate");
			return (Criteria) this;
		}

		public Criteria andDeliveryDateNotIn(List<Date> values) {
			addCriterion("delivery_date not in", values, "deliveryDate");
			return (Criteria) this;
		}

		public Criteria andDeliveryDateBetween(Date value1, Date value2) {
			addCriterion("delivery_date between", value1, value2, "deliveryDate");
			return (Criteria) this;
		}

		public Criteria andDeliveryDateNotBetween(Date value1, Date value2) {
			addCriterion("delivery_date not between", value1, value2, "deliveryDate");
			return (Criteria) this;
		}

		public Criteria andPmcStatusIsNull() {
			addCriterion("pmc_status is null");
			return (Criteria) this;
		}

		public Criteria andPmcStatusIsNotNull() {
			addCriterion("pmc_status is not null");
			return (Criteria) this;
		}

		public Criteria andPmcStatusEqualTo(String value) {
			addCriterion("pmc_status =", value, "pmcStatus");
			return (Criteria) this;
		}

		public Criteria andPmcStatusNotEqualTo(String value) {
			addCriterion("pmc_status <>", value, "pmcStatus");
			return (Criteria) this;
		}

		public Criteria andPmcStatusGreaterThan(String value) {
			addCriterion("pmc_status >", value, "pmcStatus");
			return (Criteria) this;
		}

		public Criteria andPmcStatusGreaterThanOrEqualTo(String value) {
			addCriterion("pmc_status >=", value, "pmcStatus");
			return (Criteria) this;
		}

		public Criteria andPmcStatusLessThan(String value) {
			addCriterion("pmc_status <", value, "pmcStatus");
			return (Criteria) this;
		}

		public Criteria andPmcStatusLessThanOrEqualTo(String value) {
			addCriterion("pmc_status <=", value, "pmcStatus");
			return (Criteria) this;
		}

		public Criteria andPmcStatusLike(String value) {
			addCriterion("pmc_status like", value, "pmcStatus");
			return (Criteria) this;
		}

		public Criteria andPmcStatusNotLike(String value) {
			addCriterion("pmc_status not like", value, "pmcStatus");
			return (Criteria) this;
		}

		public Criteria andPmcStatusIn(List<String> values) {
			addCriterion("pmc_status in", values, "pmcStatus");
			return (Criteria) this;
		}

		public Criteria andPmcStatusNotIn(List<String> values) {
			addCriterion("pmc_status not in", values, "pmcStatus");
			return (Criteria) this;
		}

		public Criteria andPmcStatusBetween(String value1, String value2) {
			addCriterion("pmc_status between", value1, value2, "pmcStatus");
			return (Criteria) this;
		}

		public Criteria andPmcStatusNotBetween(String value1, String value2) {
			addCriterion("pmc_status not between", value1, value2, "pmcStatus");
			return (Criteria) this;
		}

		public Criteria andQtyIsNull() {
			addCriterion("qty is null");
			return (Criteria) this;
		}

		public Criteria andQtyIsNotNull() {
			addCriterion("qty is not null");
			return (Criteria) this;
		}

		public Criteria andQtyEqualTo(Double value) {
			addCriterion("qty =", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyNotEqualTo(Double value) {
			addCriterion("qty <>", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyGreaterThan(Double value) {
			addCriterion("qty >", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyGreaterThanOrEqualTo(Double value) {
			addCriterion("qty >=", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyLessThan(Double value) {
			addCriterion("qty <", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyLessThanOrEqualTo(Double value) {
			addCriterion("qty <=", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyIn(List<Double> values) {
			addCriterion("qty in", values, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyNotIn(List<Double> values) {
			addCriterion("qty not in", values, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyBetween(Double value1, Double value2) {
			addCriterion("qty between", value1, value2, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyNotBetween(Double value1, Double value2) {
			addCriterion("qty not between", value1, value2, "qty");
			return (Criteria) this;
		}

		public Criteria andCreatedOnIsNull() {
			addCriterion("created_on is null");
			return (Criteria) this;
		}

		public Criteria andCreatedOnIsNotNull() {
			addCriterion("created_on is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedOnEqualTo(Date value) {
			addCriterion("created_on =", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnNotEqualTo(Date value) {
			addCriterion("created_on <>", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnGreaterThan(Date value) {
			addCriterion("created_on >", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnGreaterThanOrEqualTo(Date value) {
			addCriterion("created_on >=", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnLessThan(Date value) {
			addCriterion("created_on <", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnLessThanOrEqualTo(Date value) {
			addCriterion("created_on <=", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnIn(List<Date> values) {
			addCriterion("created_on in", values, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnNotIn(List<Date> values) {
			addCriterion("created_on not in", values, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnBetween(Date value1, Date value2) {
			addCriterion("created_on between", value1, value2, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnNotBetween(Date value1, Date value2) {
			addCriterion("created_on not between", value1, value2, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("code is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("code is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("code =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("code <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("code >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("code >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("code <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("code <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("code like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("code not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("code in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("code not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("code between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("code not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCreatorIsNull() {
			addCriterion("creator is null");
			return (Criteria) this;
		}

		public Criteria andCreatorIsNotNull() {
			addCriterion("creator is not null");
			return (Criteria) this;
		}

		public Criteria andCreatorEqualTo(String value) {
			addCriterion("creator =", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotEqualTo(String value) {
			addCriterion("creator <>", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorGreaterThan(String value) {
			addCriterion("creator >", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorGreaterThanOrEqualTo(String value) {
			addCriterion("creator >=", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLessThan(String value) {
			addCriterion("creator <", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLessThanOrEqualTo(String value) {
			addCriterion("creator <=", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLike(String value) {
			addCriterion("creator like", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotLike(String value) {
			addCriterion("creator not like", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorIn(List<String> values) {
			addCriterion("creator in", values, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotIn(List<String> values) {
			addCriterion("creator not in", values, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorBetween(String value1, String value2) {
			addCriterion("creator between", value1, value2, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotBetween(String value1, String value2) {
			addCriterion("creator not between", value1, value2, "creator");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table producerequestview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table producerequestview
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 19 00:03:40 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}