package com.wecloud.erp.model;

import java.util.Date;

public class ProduceNotice {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producenotice.id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producenotice.order_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producenotice.delivery_date
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Date deliveryDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producenotice.created_by
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producenotice.created_on
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Date createdOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producenotice.creator
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String creator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producenotice.qty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Double qty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producenotice.status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producenotice.pmc_status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String pmcStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producenotice.code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producenotice.reference_no
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String referenceNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producenotice.description
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producenotice.id
	 * @return  the value of producenotice.id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producenotice.id
	 * @param id  the value for producenotice.id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producenotice.order_id
	 * @return  the value of producenotice.order_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producenotice.order_id
	 * @param orderId  the value for producenotice.order_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId == null ? null : orderId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producenotice.delivery_date
	 * @return  the value of producenotice.delivery_date
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Date getDeliveryDate() {
		return deliveryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producenotice.delivery_date
	 * @param deliveryDate  the value for producenotice.delivery_date
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setDeliveryDate(Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producenotice.created_by
	 * @return  the value of producenotice.created_by
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producenotice.created_by
	 * @param createdBy  the value for producenotice.created_by
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy == null ? null : createdBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producenotice.created_on
	 * @return  the value of producenotice.created_on
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Date getCreatedOn() {
		return createdOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producenotice.created_on
	 * @param createdOn  the value for producenotice.created_on
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producenotice.creator
	 * @return  the value of producenotice.creator
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producenotice.creator
	 * @param creator  the value for producenotice.creator
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCreator(String creator) {
		this.creator = creator == null ? null : creator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producenotice.qty
	 * @return  the value of producenotice.qty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Double getQty() {
		return qty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producenotice.qty
	 * @param qty  the value for producenotice.qty
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setQty(Double qty) {
		this.qty = qty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producenotice.status
	 * @return  the value of producenotice.status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producenotice.status
	 * @param status  the value for producenotice.status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producenotice.pmc_status
	 * @return  the value of producenotice.pmc_status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getPmcStatus() {
		return pmcStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producenotice.pmc_status
	 * @param pmcStatus  the value for producenotice.pmc_status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setPmcStatus(String pmcStatus) {
		this.pmcStatus = pmcStatus == null ? null : pmcStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producenotice.code
	 * @return  the value of producenotice.code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producenotice.code
	 * @param code  the value for producenotice.code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producenotice.reference_no
	 * @return  the value of producenotice.reference_no
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getReferenceNo() {
		return referenceNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producenotice.reference_no
	 * @param referenceNo  the value for producenotice.reference_no
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setReferenceNo(String referenceNo) {
		this.referenceNo = referenceNo == null ? null : referenceNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producenotice.description
	 * @return  the value of producenotice.description
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producenotice.description
	 * @param description  the value for producenotice.description
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}
}