package com.wecloud.erp.model;

import java.util.Date;

public class QcRequest {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrequest.ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrequest.CODE
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrequest.NAME
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrequest.ORDER_ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrequest.DELIVERY_DATE
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Date deliveryDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrequest.SUPPLIER_ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String supplierId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrequest.SUPPLIER_NAME
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String supplierName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrequest.AMOUNT
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Double amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrequest.QTY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Double qty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrequest.PASSED_QTY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Double passedQty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrequest.FAILED_QTY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Double failedQty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrequest.CREATOR
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String creator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrequest.CREATED_ON
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Date createdOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrequest.CREATED_BY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrequest.qc_status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String qcStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrequest.reference_no
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String referenceNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrequest.description
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrequest.ID
	 * @return  the value of qcrequest.ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrequest.ID
	 * @param id  the value for qcrequest.ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrequest.CODE
	 * @return  the value of qcrequest.CODE
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrequest.CODE
	 * @param code  the value for qcrequest.CODE
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrequest.NAME
	 * @return  the value of qcrequest.NAME
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrequest.NAME
	 * @param name  the value for qcrequest.NAME
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrequest.ORDER_ID
	 * @return  the value of qcrequest.ORDER_ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrequest.ORDER_ID
	 * @param orderId  the value for qcrequest.ORDER_ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId == null ? null : orderId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrequest.DELIVERY_DATE
	 * @return  the value of qcrequest.DELIVERY_DATE
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Date getDeliveryDate() {
		return deliveryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrequest.DELIVERY_DATE
	 * @param deliveryDate  the value for qcrequest.DELIVERY_DATE
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setDeliveryDate(Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrequest.SUPPLIER_ID
	 * @return  the value of qcrequest.SUPPLIER_ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getSupplierId() {
		return supplierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrequest.SUPPLIER_ID
	 * @param supplierId  the value for qcrequest.SUPPLIER_ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setSupplierId(String supplierId) {
		this.supplierId = supplierId == null ? null : supplierId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrequest.SUPPLIER_NAME
	 * @return  the value of qcrequest.SUPPLIER_NAME
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getSupplierName() {
		return supplierName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrequest.SUPPLIER_NAME
	 * @param supplierName  the value for qcrequest.SUPPLIER_NAME
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName == null ? null : supplierName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrequest.AMOUNT
	 * @return  the value of qcrequest.AMOUNT
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Double getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrequest.AMOUNT
	 * @param amount  the value for qcrequest.AMOUNT
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setAmount(Double amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrequest.QTY
	 * @return  the value of qcrequest.QTY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Double getQty() {
		return qty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrequest.QTY
	 * @param qty  the value for qcrequest.QTY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setQty(Double qty) {
		this.qty = qty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrequest.PASSED_QTY
	 * @return  the value of qcrequest.PASSED_QTY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Double getPassedQty() {
		return passedQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrequest.PASSED_QTY
	 * @param passedQty  the value for qcrequest.PASSED_QTY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setPassedQty(Double passedQty) {
		this.passedQty = passedQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrequest.FAILED_QTY
	 * @return  the value of qcrequest.FAILED_QTY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Double getFailedQty() {
		return failedQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrequest.FAILED_QTY
	 * @param failedQty  the value for qcrequest.FAILED_QTY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setFailedQty(Double failedQty) {
		this.failedQty = failedQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrequest.CREATOR
	 * @return  the value of qcrequest.CREATOR
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrequest.CREATOR
	 * @param creator  the value for qcrequest.CREATOR
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCreator(String creator) {
		this.creator = creator == null ? null : creator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrequest.CREATED_ON
	 * @return  the value of qcrequest.CREATED_ON
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Date getCreatedOn() {
		return createdOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrequest.CREATED_ON
	 * @param createdOn  the value for qcrequest.CREATED_ON
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrequest.CREATED_BY
	 * @return  the value of qcrequest.CREATED_BY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrequest.CREATED_BY
	 * @param createdBy  the value for qcrequest.CREATED_BY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy == null ? null : createdBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrequest.qc_status
	 * @return  the value of qcrequest.qc_status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getQcStatus() {
		return qcStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrequest.qc_status
	 * @param qcStatus  the value for qcrequest.qc_status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setQcStatus(String qcStatus) {
		this.qcStatus = qcStatus == null ? null : qcStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrequest.reference_no
	 * @return  the value of qcrequest.reference_no
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getReferenceNo() {
		return referenceNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrequest.reference_no
	 * @param referenceNo  the value for qcrequest.reference_no
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setReferenceNo(String referenceNo) {
		this.referenceNo = referenceNo == null ? null : referenceNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrequest.description
	 * @return  the value of qcrequest.description
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrequest.description
	 * @param description  the value for qcrequest.description
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}
}