package com.wecloud.erp.model;

public class QcRecordItem {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrecorditem.ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrecorditem.CODE
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrecorditem.NAME
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrecorditem.RECORD_ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String recordId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrecorditem.ITEM_ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String itemId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrecorditem.AMOUNT
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Double amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrecorditem.QTY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Double qty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrecorditem.uom
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String uom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrecorditem.PASSED_QTY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Double passedQty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrecorditem.FAILED_QTY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Double failedQty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrecorditem.QC_STATUS
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String qcStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrecorditem.description
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qcrecorditem.style
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String style;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrecorditem.ID
	 * @return  the value of qcrecorditem.ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrecorditem.ID
	 * @param id  the value for qcrecorditem.ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrecorditem.CODE
	 * @return  the value of qcrecorditem.CODE
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrecorditem.CODE
	 * @param code  the value for qcrecorditem.CODE
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrecorditem.NAME
	 * @return  the value of qcrecorditem.NAME
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrecorditem.NAME
	 * @param name  the value for qcrecorditem.NAME
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrecorditem.RECORD_ID
	 * @return  the value of qcrecorditem.RECORD_ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getRecordId() {
		return recordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrecorditem.RECORD_ID
	 * @param recordId  the value for qcrecorditem.RECORD_ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setRecordId(String recordId) {
		this.recordId = recordId == null ? null : recordId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrecorditem.ITEM_ID
	 * @return  the value of qcrecorditem.ITEM_ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getItemId() {
		return itemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrecorditem.ITEM_ID
	 * @param itemId  the value for qcrecorditem.ITEM_ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setItemId(String itemId) {
		this.itemId = itemId == null ? null : itemId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrecorditem.AMOUNT
	 * @return  the value of qcrecorditem.AMOUNT
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Double getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrecorditem.AMOUNT
	 * @param amount  the value for qcrecorditem.AMOUNT
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setAmount(Double amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrecorditem.QTY
	 * @return  the value of qcrecorditem.QTY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Double getQty() {
		return qty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrecorditem.QTY
	 * @param qty  the value for qcrecorditem.QTY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setQty(Double qty) {
		this.qty = qty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrecorditem.uom
	 * @return  the value of qcrecorditem.uom
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getUom() {
		return uom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrecorditem.uom
	 * @param uom  the value for qcrecorditem.uom
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setUom(String uom) {
		this.uom = uom == null ? null : uom.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrecorditem.PASSED_QTY
	 * @return  the value of qcrecorditem.PASSED_QTY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Double getPassedQty() {
		return passedQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrecorditem.PASSED_QTY
	 * @param passedQty  the value for qcrecorditem.PASSED_QTY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setPassedQty(Double passedQty) {
		this.passedQty = passedQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrecorditem.FAILED_QTY
	 * @return  the value of qcrecorditem.FAILED_QTY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Double getFailedQty() {
		return failedQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrecorditem.FAILED_QTY
	 * @param failedQty  the value for qcrecorditem.FAILED_QTY
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setFailedQty(Double failedQty) {
		this.failedQty = failedQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrecorditem.QC_STATUS
	 * @return  the value of qcrecorditem.QC_STATUS
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getQcStatus() {
		return qcStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrecorditem.QC_STATUS
	 * @param qcStatus  the value for qcrecorditem.QC_STATUS
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setQcStatus(String qcStatus) {
		this.qcStatus = qcStatus == null ? null : qcStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrecorditem.description
	 * @return  the value of qcrecorditem.description
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrecorditem.description
	 * @param description  the value for qcrecorditem.description
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qcrecorditem.style
	 * @return  the value of qcrecorditem.style
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getStyle() {
		return style;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qcrecorditem.style
	 * @param style  the value for qcrecorditem.style
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setStyle(String style) {
		this.style = style == null ? null : style.trim();
	}
}