package com.wecloud.erp.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class QcRecordExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table qcrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table qcrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table qcrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table qcrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected String limitStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table qcrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected String limitEnd;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qcrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public QcRecordExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qcrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qcrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qcrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qcrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qcrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qcrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qcrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qcrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qcrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qcrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qcrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setLimitStart(String limitStart) {
		this.limitStart = limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qcrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getLimitStart() {
		return limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qcrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setLimitEnd(String limitEnd) {
		this.limitEnd = limitEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qcrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getLimitEnd() {
		return limitEnd;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table qcrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("CODE is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("CODE is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("CODE =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("CODE <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("CODE >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("CODE >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("CODE <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("CODE <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("CODE like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("CODE not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("CODE in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("CODE not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("CODE between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("CODE not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("NAME is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("NAME is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("NAME =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("NAME <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("NAME >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("NAME >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("NAME <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("NAME <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("NAME like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("NAME not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("NAME in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("NAME not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("NAME between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("NAME not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andRequestIdIsNull() {
			addCriterion("REQUEST_ID is null");
			return (Criteria) this;
		}

		public Criteria andRequestIdIsNotNull() {
			addCriterion("REQUEST_ID is not null");
			return (Criteria) this;
		}

		public Criteria andRequestIdEqualTo(String value) {
			addCriterion("REQUEST_ID =", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdNotEqualTo(String value) {
			addCriterion("REQUEST_ID <>", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdGreaterThan(String value) {
			addCriterion("REQUEST_ID >", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdGreaterThanOrEqualTo(String value) {
			addCriterion("REQUEST_ID >=", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdLessThan(String value) {
			addCriterion("REQUEST_ID <", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdLessThanOrEqualTo(String value) {
			addCriterion("REQUEST_ID <=", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdLike(String value) {
			addCriterion("REQUEST_ID like", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdNotLike(String value) {
			addCriterion("REQUEST_ID not like", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdIn(List<String> values) {
			addCriterion("REQUEST_ID in", values, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdNotIn(List<String> values) {
			addCriterion("REQUEST_ID not in", values, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdBetween(String value1, String value2) {
			addCriterion("REQUEST_ID between", value1, value2, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdNotBetween(String value1, String value2) {
			addCriterion("REQUEST_ID not between", value1, value2, "requestId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdIsNull() {
			addCriterion("SUPPLIER_ID is null");
			return (Criteria) this;
		}

		public Criteria andSupplierIdIsNotNull() {
			addCriterion("SUPPLIER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andSupplierIdEqualTo(String value) {
			addCriterion("SUPPLIER_ID =", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdNotEqualTo(String value) {
			addCriterion("SUPPLIER_ID <>", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdGreaterThan(String value) {
			addCriterion("SUPPLIER_ID >", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdGreaterThanOrEqualTo(String value) {
			addCriterion("SUPPLIER_ID >=", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdLessThan(String value) {
			addCriterion("SUPPLIER_ID <", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdLessThanOrEqualTo(String value) {
			addCriterion("SUPPLIER_ID <=", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdLike(String value) {
			addCriterion("SUPPLIER_ID like", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdNotLike(String value) {
			addCriterion("SUPPLIER_ID not like", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdIn(List<String> values) {
			addCriterion("SUPPLIER_ID in", values, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdNotIn(List<String> values) {
			addCriterion("SUPPLIER_ID not in", values, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdBetween(String value1, String value2) {
			addCriterion("SUPPLIER_ID between", value1, value2, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdNotBetween(String value1, String value2) {
			addCriterion("SUPPLIER_ID not between", value1, value2, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierNameIsNull() {
			addCriterion("SUPPLIER_NAME is null");
			return (Criteria) this;
		}

		public Criteria andSupplierNameIsNotNull() {
			addCriterion("SUPPLIER_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andSupplierNameEqualTo(String value) {
			addCriterion("SUPPLIER_NAME =", value, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameNotEqualTo(String value) {
			addCriterion("SUPPLIER_NAME <>", value, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameGreaterThan(String value) {
			addCriterion("SUPPLIER_NAME >", value, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameGreaterThanOrEqualTo(String value) {
			addCriterion("SUPPLIER_NAME >=", value, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameLessThan(String value) {
			addCriterion("SUPPLIER_NAME <", value, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameLessThanOrEqualTo(String value) {
			addCriterion("SUPPLIER_NAME <=", value, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameLike(String value) {
			addCriterion("SUPPLIER_NAME like", value, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameNotLike(String value) {
			addCriterion("SUPPLIER_NAME not like", value, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameIn(List<String> values) {
			addCriterion("SUPPLIER_NAME in", values, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameNotIn(List<String> values) {
			addCriterion("SUPPLIER_NAME not in", values, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameBetween(String value1, String value2) {
			addCriterion("SUPPLIER_NAME between", value1, value2, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameNotBetween(String value1, String value2) {
			addCriterion("SUPPLIER_NAME not between", value1, value2, "supplierName");
			return (Criteria) this;
		}

		public Criteria andQtyIsNull() {
			addCriterion("QTY is null");
			return (Criteria) this;
		}

		public Criteria andQtyIsNotNull() {
			addCriterion("QTY is not null");
			return (Criteria) this;
		}

		public Criteria andQtyEqualTo(Double value) {
			addCriterion("QTY =", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyNotEqualTo(Double value) {
			addCriterion("QTY <>", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyGreaterThan(Double value) {
			addCriterion("QTY >", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyGreaterThanOrEqualTo(Double value) {
			addCriterion("QTY >=", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyLessThan(Double value) {
			addCriterion("QTY <", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyLessThanOrEqualTo(Double value) {
			addCriterion("QTY <=", value, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyIn(List<Double> values) {
			addCriterion("QTY in", values, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyNotIn(List<Double> values) {
			addCriterion("QTY not in", values, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyBetween(Double value1, Double value2) {
			addCriterion("QTY between", value1, value2, "qty");
			return (Criteria) this;
		}

		public Criteria andQtyNotBetween(Double value1, Double value2) {
			addCriterion("QTY not between", value1, value2, "qty");
			return (Criteria) this;
		}

		public Criteria andPassedQtyIsNull() {
			addCriterion("PASSED_QTY is null");
			return (Criteria) this;
		}

		public Criteria andPassedQtyIsNotNull() {
			addCriterion("PASSED_QTY is not null");
			return (Criteria) this;
		}

		public Criteria andPassedQtyEqualTo(Double value) {
			addCriterion("PASSED_QTY =", value, "passedQty");
			return (Criteria) this;
		}

		public Criteria andPassedQtyNotEqualTo(Double value) {
			addCriterion("PASSED_QTY <>", value, "passedQty");
			return (Criteria) this;
		}

		public Criteria andPassedQtyGreaterThan(Double value) {
			addCriterion("PASSED_QTY >", value, "passedQty");
			return (Criteria) this;
		}

		public Criteria andPassedQtyGreaterThanOrEqualTo(Double value) {
			addCriterion("PASSED_QTY >=", value, "passedQty");
			return (Criteria) this;
		}

		public Criteria andPassedQtyLessThan(Double value) {
			addCriterion("PASSED_QTY <", value, "passedQty");
			return (Criteria) this;
		}

		public Criteria andPassedQtyLessThanOrEqualTo(Double value) {
			addCriterion("PASSED_QTY <=", value, "passedQty");
			return (Criteria) this;
		}

		public Criteria andPassedQtyIn(List<Double> values) {
			addCriterion("PASSED_QTY in", values, "passedQty");
			return (Criteria) this;
		}

		public Criteria andPassedQtyNotIn(List<Double> values) {
			addCriterion("PASSED_QTY not in", values, "passedQty");
			return (Criteria) this;
		}

		public Criteria andPassedQtyBetween(Double value1, Double value2) {
			addCriterion("PASSED_QTY between", value1, value2, "passedQty");
			return (Criteria) this;
		}

		public Criteria andPassedQtyNotBetween(Double value1, Double value2) {
			addCriterion("PASSED_QTY not between", value1, value2, "passedQty");
			return (Criteria) this;
		}

		public Criteria andFailedQtyIsNull() {
			addCriterion("FAILED_QTY is null");
			return (Criteria) this;
		}

		public Criteria andFailedQtyIsNotNull() {
			addCriterion("FAILED_QTY is not null");
			return (Criteria) this;
		}

		public Criteria andFailedQtyEqualTo(Double value) {
			addCriterion("FAILED_QTY =", value, "failedQty");
			return (Criteria) this;
		}

		public Criteria andFailedQtyNotEqualTo(Double value) {
			addCriterion("FAILED_QTY <>", value, "failedQty");
			return (Criteria) this;
		}

		public Criteria andFailedQtyGreaterThan(Double value) {
			addCriterion("FAILED_QTY >", value, "failedQty");
			return (Criteria) this;
		}

		public Criteria andFailedQtyGreaterThanOrEqualTo(Double value) {
			addCriterion("FAILED_QTY >=", value, "failedQty");
			return (Criteria) this;
		}

		public Criteria andFailedQtyLessThan(Double value) {
			addCriterion("FAILED_QTY <", value, "failedQty");
			return (Criteria) this;
		}

		public Criteria andFailedQtyLessThanOrEqualTo(Double value) {
			addCriterion("FAILED_QTY <=", value, "failedQty");
			return (Criteria) this;
		}

		public Criteria andFailedQtyIn(List<Double> values) {
			addCriterion("FAILED_QTY in", values, "failedQty");
			return (Criteria) this;
		}

		public Criteria andFailedQtyNotIn(List<Double> values) {
			addCriterion("FAILED_QTY not in", values, "failedQty");
			return (Criteria) this;
		}

		public Criteria andFailedQtyBetween(Double value1, Double value2) {
			addCriterion("FAILED_QTY between", value1, value2, "failedQty");
			return (Criteria) this;
		}

		public Criteria andFailedQtyNotBetween(Double value1, Double value2) {
			addCriterion("FAILED_QTY not between", value1, value2, "failedQty");
			return (Criteria) this;
		}

		public Criteria andCreatorIsNull() {
			addCriterion("CREATOR is null");
			return (Criteria) this;
		}

		public Criteria andCreatorIsNotNull() {
			addCriterion("CREATOR is not null");
			return (Criteria) this;
		}

		public Criteria andCreatorEqualTo(String value) {
			addCriterion("CREATOR =", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotEqualTo(String value) {
			addCriterion("CREATOR <>", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorGreaterThan(String value) {
			addCriterion("CREATOR >", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorGreaterThanOrEqualTo(String value) {
			addCriterion("CREATOR >=", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLessThan(String value) {
			addCriterion("CREATOR <", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLessThanOrEqualTo(String value) {
			addCriterion("CREATOR <=", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLike(String value) {
			addCriterion("CREATOR like", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotLike(String value) {
			addCriterion("CREATOR not like", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorIn(List<String> values) {
			addCriterion("CREATOR in", values, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotIn(List<String> values) {
			addCriterion("CREATOR not in", values, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorBetween(String value1, String value2) {
			addCriterion("CREATOR between", value1, value2, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotBetween(String value1, String value2) {
			addCriterion("CREATOR not between", value1, value2, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatedOnIsNull() {
			addCriterion("CREATED_ON is null");
			return (Criteria) this;
		}

		public Criteria andCreatedOnIsNotNull() {
			addCriterion("CREATED_ON is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedOnEqualTo(Date value) {
			addCriterionForJDBCDate("CREATED_ON =", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnNotEqualTo(Date value) {
			addCriterionForJDBCDate("CREATED_ON <>", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnGreaterThan(Date value) {
			addCriterionForJDBCDate("CREATED_ON >", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATED_ON >=", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnLessThan(Date value) {
			addCriterionForJDBCDate("CREATED_ON <", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATED_ON <=", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnIn(List<Date> values) {
			addCriterionForJDBCDate("CREATED_ON in", values, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnNotIn(List<Date> values) {
			addCriterionForJDBCDate("CREATED_ON not in", values, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATED_ON between", value1, value2, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATED_ON not between", value1, value2, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedByIsNull() {
			addCriterion("CREATED_BY is null");
			return (Criteria) this;
		}

		public Criteria andCreatedByIsNotNull() {
			addCriterion("CREATED_BY is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedByEqualTo(String value) {
			addCriterion("CREATED_BY =", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotEqualTo(String value) {
			addCriterion("CREATED_BY <>", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByGreaterThan(String value) {
			addCriterion("CREATED_BY >", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
			addCriterion("CREATED_BY >=", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByLessThan(String value) {
			addCriterion("CREATED_BY <", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByLessThanOrEqualTo(String value) {
			addCriterion("CREATED_BY <=", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByLike(String value) {
			addCriterion("CREATED_BY like", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotLike(String value) {
			addCriterion("CREATED_BY not like", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByIn(List<String> values) {
			addCriterion("CREATED_BY in", values, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotIn(List<String> values) {
			addCriterion("CREATED_BY not in", values, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByBetween(String value1, String value2) {
			addCriterion("CREATED_BY between", value1, value2, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotBetween(String value1, String value2) {
			addCriterion("CREATED_BY not between", value1, value2, "createdBy");
			return (Criteria) this;
		}

		public Criteria andQcStatusIsNull() {
			addCriterion("qc_status is null");
			return (Criteria) this;
		}

		public Criteria andQcStatusIsNotNull() {
			addCriterion("qc_status is not null");
			return (Criteria) this;
		}

		public Criteria andQcStatusEqualTo(String value) {
			addCriterion("qc_status =", value, "qcStatus");
			return (Criteria) this;
		}

		public Criteria andQcStatusNotEqualTo(String value) {
			addCriterion("qc_status <>", value, "qcStatus");
			return (Criteria) this;
		}

		public Criteria andQcStatusGreaterThan(String value) {
			addCriterion("qc_status >", value, "qcStatus");
			return (Criteria) this;
		}

		public Criteria andQcStatusGreaterThanOrEqualTo(String value) {
			addCriterion("qc_status >=", value, "qcStatus");
			return (Criteria) this;
		}

		public Criteria andQcStatusLessThan(String value) {
			addCriterion("qc_status <", value, "qcStatus");
			return (Criteria) this;
		}

		public Criteria andQcStatusLessThanOrEqualTo(String value) {
			addCriterion("qc_status <=", value, "qcStatus");
			return (Criteria) this;
		}

		public Criteria andQcStatusLike(String value) {
			addCriterion("qc_status like", value, "qcStatus");
			return (Criteria) this;
		}

		public Criteria andQcStatusNotLike(String value) {
			addCriterion("qc_status not like", value, "qcStatus");
			return (Criteria) this;
		}

		public Criteria andQcStatusIn(List<String> values) {
			addCriterion("qc_status in", values, "qcStatus");
			return (Criteria) this;
		}

		public Criteria andQcStatusNotIn(List<String> values) {
			addCriterion("qc_status not in", values, "qcStatus");
			return (Criteria) this;
		}

		public Criteria andQcStatusBetween(String value1, String value2) {
			addCriterion("qc_status between", value1, value2, "qcStatus");
			return (Criteria) this;
		}

		public Criteria andQcStatusNotBetween(String value1, String value2) {
			addCriterion("qc_status not between", value1, value2, "qcStatus");
			return (Criteria) this;
		}

		public Criteria andReferenceNoIsNull() {
			addCriterion("reference_no is null");
			return (Criteria) this;
		}

		public Criteria andReferenceNoIsNotNull() {
			addCriterion("reference_no is not null");
			return (Criteria) this;
		}

		public Criteria andReferenceNoEqualTo(String value) {
			addCriterion("reference_no =", value, "referenceNo");
			return (Criteria) this;
		}

		public Criteria andReferenceNoNotEqualTo(String value) {
			addCriterion("reference_no <>", value, "referenceNo");
			return (Criteria) this;
		}

		public Criteria andReferenceNoGreaterThan(String value) {
			addCriterion("reference_no >", value, "referenceNo");
			return (Criteria) this;
		}

		public Criteria andReferenceNoGreaterThanOrEqualTo(String value) {
			addCriterion("reference_no >=", value, "referenceNo");
			return (Criteria) this;
		}

		public Criteria andReferenceNoLessThan(String value) {
			addCriterion("reference_no <", value, "referenceNo");
			return (Criteria) this;
		}

		public Criteria andReferenceNoLessThanOrEqualTo(String value) {
			addCriterion("reference_no <=", value, "referenceNo");
			return (Criteria) this;
		}

		public Criteria andReferenceNoLike(String value) {
			addCriterion("reference_no like", value, "referenceNo");
			return (Criteria) this;
		}

		public Criteria andReferenceNoNotLike(String value) {
			addCriterion("reference_no not like", value, "referenceNo");
			return (Criteria) this;
		}

		public Criteria andReferenceNoIn(List<String> values) {
			addCriterion("reference_no in", values, "referenceNo");
			return (Criteria) this;
		}

		public Criteria andReferenceNoNotIn(List<String> values) {
			addCriterion("reference_no not in", values, "referenceNo");
			return (Criteria) this;
		}

		public Criteria andReferenceNoBetween(String value1, String value2) {
			addCriterion("reference_no between", value1, value2, "referenceNo");
			return (Criteria) this;
		}

		public Criteria andReferenceNoNotBetween(String value1, String value2) {
			addCriterion("reference_no not between", value1, value2, "referenceNo");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table qcrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table qcrecord
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 19 00:03:40 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}