package com.wecloud.erp.model;

import java.util.Date;

public class SplitItemView {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column splititemview.id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column splititemview.name
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column splititemview.code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column splititemview.type
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column splititemview.style
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String style;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column splititemview.pack_type
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String packType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column splititemview.uom
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String uom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column splititemview.picture
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String picture;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column splititemview.order_uom
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String orderUom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column splititemview.order_price
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Double orderPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column splititemview.sale_price
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Double salePrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column splititemview.brand
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String brand;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column splititemview.created_by
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column splititemview.created_on
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Date createdOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column splititemview.status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column splititemview.is_baseitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Integer isBaseitem;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column splititemview.codelist
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String codelist;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column splititemview.source_code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String sourceCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column splititemview.class_code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String classCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column splititemview.supplier_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String supplierId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column splititemview.supplier_name
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String supplierName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column splititemview.remark
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column splititemview.id
	 * @return  the value of splititemview.id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column splititemview.id
	 * @param id  the value for splititemview.id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column splititemview.name
	 * @return  the value of splititemview.name
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column splititemview.name
	 * @param name  the value for splititemview.name
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column splititemview.code
	 * @return  the value of splititemview.code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column splititemview.code
	 * @param code  the value for splititemview.code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column splititemview.type
	 * @return  the value of splititemview.type
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column splititemview.type
	 * @param type  the value for splititemview.type
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column splititemview.style
	 * @return  the value of splititemview.style
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getStyle() {
		return style;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column splititemview.style
	 * @param style  the value for splititemview.style
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setStyle(String style) {
		this.style = style == null ? null : style.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column splititemview.pack_type
	 * @return  the value of splititemview.pack_type
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getPackType() {
		return packType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column splititemview.pack_type
	 * @param packType  the value for splititemview.pack_type
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setPackType(String packType) {
		this.packType = packType == null ? null : packType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column splititemview.uom
	 * @return  the value of splititemview.uom
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getUom() {
		return uom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column splititemview.uom
	 * @param uom  the value for splititemview.uom
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setUom(String uom) {
		this.uom = uom == null ? null : uom.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column splititemview.picture
	 * @return  the value of splititemview.picture
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getPicture() {
		return picture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column splititemview.picture
	 * @param picture  the value for splititemview.picture
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setPicture(String picture) {
		this.picture = picture == null ? null : picture.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column splititemview.order_uom
	 * @return  the value of splititemview.order_uom
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getOrderUom() {
		return orderUom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column splititemview.order_uom
	 * @param orderUom  the value for splititemview.order_uom
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setOrderUom(String orderUom) {
		this.orderUom = orderUom == null ? null : orderUom.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column splititemview.order_price
	 * @return  the value of splititemview.order_price
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Double getOrderPrice() {
		return orderPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column splititemview.order_price
	 * @param orderPrice  the value for splititemview.order_price
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setOrderPrice(Double orderPrice) {
		this.orderPrice = orderPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column splititemview.sale_price
	 * @return  the value of splititemview.sale_price
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Double getSalePrice() {
		return salePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column splititemview.sale_price
	 * @param salePrice  the value for splititemview.sale_price
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setSalePrice(Double salePrice) {
		this.salePrice = salePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column splititemview.brand
	 * @return  the value of splititemview.brand
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getBrand() {
		return brand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column splititemview.brand
	 * @param brand  the value for splititemview.brand
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setBrand(String brand) {
		this.brand = brand == null ? null : brand.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column splititemview.created_by
	 * @return  the value of splititemview.created_by
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column splititemview.created_by
	 * @param createdBy  the value for splititemview.created_by
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy == null ? null : createdBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column splititemview.created_on
	 * @return  the value of splititemview.created_on
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Date getCreatedOn() {
		return createdOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column splititemview.created_on
	 * @param createdOn  the value for splititemview.created_on
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column splititemview.status
	 * @return  the value of splititemview.status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column splititemview.status
	 * @param status  the value for splititemview.status
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column splititemview.is_baseitem
	 * @return  the value of splititemview.is_baseitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Integer getIsBaseitem() {
		return isBaseitem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column splititemview.is_baseitem
	 * @param isBaseitem  the value for splititemview.is_baseitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setIsBaseitem(Integer isBaseitem) {
		this.isBaseitem = isBaseitem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column splititemview.codelist
	 * @return  the value of splititemview.codelist
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getCodelist() {
		return codelist;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column splititemview.codelist
	 * @param codelist  the value for splititemview.codelist
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setCodelist(String codelist) {
		this.codelist = codelist == null ? null : codelist.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column splititemview.source_code
	 * @return  the value of splititemview.source_code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getSourceCode() {
		return sourceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column splititemview.source_code
	 * @param sourceCode  the value for splititemview.source_code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setSourceCode(String sourceCode) {
		this.sourceCode = sourceCode == null ? null : sourceCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column splititemview.class_code
	 * @return  the value of splititemview.class_code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getClassCode() {
		return classCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column splititemview.class_code
	 * @param classCode  the value for splititemview.class_code
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setClassCode(String classCode) {
		this.classCode = classCode == null ? null : classCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column splititemview.supplier_id
	 * @return  the value of splititemview.supplier_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getSupplierId() {
		return supplierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column splititemview.supplier_id
	 * @param supplierId  the value for splititemview.supplier_id
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setSupplierId(String supplierId) {
		this.supplierId = supplierId == null ? null : supplierId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column splititemview.supplier_name
	 * @return  the value of splititemview.supplier_name
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getSupplierName() {
		return supplierName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column splititemview.supplier_name
	 * @param supplierName  the value for splititemview.supplier_name
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName == null ? null : supplierName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column splititemview.remark
	 * @return  the value of splititemview.remark
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column splititemview.remark
	 * @param remark  the value for splititemview.remark
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}