package com.wecloud.erp.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SplitItemViewExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table splititemview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table splititemview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table splititemview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table splititemview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected String limitStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table splititemview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected String limitEnd;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table splititemview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public SplitItemViewExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table splititemview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table splititemview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table splititemview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table splititemview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table splititemview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table splititemview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table splititemview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table splititemview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table splititemview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table splititemview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table splititemview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setLimitStart(String limitStart) {
		this.limitStart = limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table splititemview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getLimitStart() {
		return limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table splititemview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setLimitEnd(String limitEnd) {
		this.limitEnd = limitEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table splititemview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getLimitEnd() {
		return limitEnd;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table splititemview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("code is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("code is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("code =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("code <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("code >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("code >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("code <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("code <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("code like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("code not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("code in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("code not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("code between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("code not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(String value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(String value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(String value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(String value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(String value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(String value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLike(String value) {
			addCriterion("type like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotLike(String value) {
			addCriterion("type not like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<String> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<String> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(String value1, String value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(String value1, String value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andStyleIsNull() {
			addCriterion("style is null");
			return (Criteria) this;
		}

		public Criteria andStyleIsNotNull() {
			addCriterion("style is not null");
			return (Criteria) this;
		}

		public Criteria andStyleEqualTo(String value) {
			addCriterion("style =", value, "style");
			return (Criteria) this;
		}

		public Criteria andStyleNotEqualTo(String value) {
			addCriterion("style <>", value, "style");
			return (Criteria) this;
		}

		public Criteria andStyleGreaterThan(String value) {
			addCriterion("style >", value, "style");
			return (Criteria) this;
		}

		public Criteria andStyleGreaterThanOrEqualTo(String value) {
			addCriterion("style >=", value, "style");
			return (Criteria) this;
		}

		public Criteria andStyleLessThan(String value) {
			addCriterion("style <", value, "style");
			return (Criteria) this;
		}

		public Criteria andStyleLessThanOrEqualTo(String value) {
			addCriterion("style <=", value, "style");
			return (Criteria) this;
		}

		public Criteria andStyleLike(String value) {
			addCriterion("style like", value, "style");
			return (Criteria) this;
		}

		public Criteria andStyleNotLike(String value) {
			addCriterion("style not like", value, "style");
			return (Criteria) this;
		}

		public Criteria andStyleIn(List<String> values) {
			addCriterion("style in", values, "style");
			return (Criteria) this;
		}

		public Criteria andStyleNotIn(List<String> values) {
			addCriterion("style not in", values, "style");
			return (Criteria) this;
		}

		public Criteria andStyleBetween(String value1, String value2) {
			addCriterion("style between", value1, value2, "style");
			return (Criteria) this;
		}

		public Criteria andStyleNotBetween(String value1, String value2) {
			addCriterion("style not between", value1, value2, "style");
			return (Criteria) this;
		}

		public Criteria andPackTypeIsNull() {
			addCriterion("pack_type is null");
			return (Criteria) this;
		}

		public Criteria andPackTypeIsNotNull() {
			addCriterion("pack_type is not null");
			return (Criteria) this;
		}

		public Criteria andPackTypeEqualTo(String value) {
			addCriterion("pack_type =", value, "packType");
			return (Criteria) this;
		}

		public Criteria andPackTypeNotEqualTo(String value) {
			addCriterion("pack_type <>", value, "packType");
			return (Criteria) this;
		}

		public Criteria andPackTypeGreaterThan(String value) {
			addCriterion("pack_type >", value, "packType");
			return (Criteria) this;
		}

		public Criteria andPackTypeGreaterThanOrEqualTo(String value) {
			addCriterion("pack_type >=", value, "packType");
			return (Criteria) this;
		}

		public Criteria andPackTypeLessThan(String value) {
			addCriterion("pack_type <", value, "packType");
			return (Criteria) this;
		}

		public Criteria andPackTypeLessThanOrEqualTo(String value) {
			addCriterion("pack_type <=", value, "packType");
			return (Criteria) this;
		}

		public Criteria andPackTypeLike(String value) {
			addCriterion("pack_type like", value, "packType");
			return (Criteria) this;
		}

		public Criteria andPackTypeNotLike(String value) {
			addCriterion("pack_type not like", value, "packType");
			return (Criteria) this;
		}

		public Criteria andPackTypeIn(List<String> values) {
			addCriterion("pack_type in", values, "packType");
			return (Criteria) this;
		}

		public Criteria andPackTypeNotIn(List<String> values) {
			addCriterion("pack_type not in", values, "packType");
			return (Criteria) this;
		}

		public Criteria andPackTypeBetween(String value1, String value2) {
			addCriterion("pack_type between", value1, value2, "packType");
			return (Criteria) this;
		}

		public Criteria andPackTypeNotBetween(String value1, String value2) {
			addCriterion("pack_type not between", value1, value2, "packType");
			return (Criteria) this;
		}

		public Criteria andUomIsNull() {
			addCriterion("uom is null");
			return (Criteria) this;
		}

		public Criteria andUomIsNotNull() {
			addCriterion("uom is not null");
			return (Criteria) this;
		}

		public Criteria andUomEqualTo(String value) {
			addCriterion("uom =", value, "uom");
			return (Criteria) this;
		}

		public Criteria andUomNotEqualTo(String value) {
			addCriterion("uom <>", value, "uom");
			return (Criteria) this;
		}

		public Criteria andUomGreaterThan(String value) {
			addCriterion("uom >", value, "uom");
			return (Criteria) this;
		}

		public Criteria andUomGreaterThanOrEqualTo(String value) {
			addCriterion("uom >=", value, "uom");
			return (Criteria) this;
		}

		public Criteria andUomLessThan(String value) {
			addCriterion("uom <", value, "uom");
			return (Criteria) this;
		}

		public Criteria andUomLessThanOrEqualTo(String value) {
			addCriterion("uom <=", value, "uom");
			return (Criteria) this;
		}

		public Criteria andUomLike(String value) {
			addCriterion("uom like", value, "uom");
			return (Criteria) this;
		}

		public Criteria andUomNotLike(String value) {
			addCriterion("uom not like", value, "uom");
			return (Criteria) this;
		}

		public Criteria andUomIn(List<String> values) {
			addCriterion("uom in", values, "uom");
			return (Criteria) this;
		}

		public Criteria andUomNotIn(List<String> values) {
			addCriterion("uom not in", values, "uom");
			return (Criteria) this;
		}

		public Criteria andUomBetween(String value1, String value2) {
			addCriterion("uom between", value1, value2, "uom");
			return (Criteria) this;
		}

		public Criteria andUomNotBetween(String value1, String value2) {
			addCriterion("uom not between", value1, value2, "uom");
			return (Criteria) this;
		}

		public Criteria andPictureIsNull() {
			addCriterion("picture is null");
			return (Criteria) this;
		}

		public Criteria andPictureIsNotNull() {
			addCriterion("picture is not null");
			return (Criteria) this;
		}

		public Criteria andPictureEqualTo(String value) {
			addCriterion("picture =", value, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureNotEqualTo(String value) {
			addCriterion("picture <>", value, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureGreaterThan(String value) {
			addCriterion("picture >", value, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureGreaterThanOrEqualTo(String value) {
			addCriterion("picture >=", value, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureLessThan(String value) {
			addCriterion("picture <", value, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureLessThanOrEqualTo(String value) {
			addCriterion("picture <=", value, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureLike(String value) {
			addCriterion("picture like", value, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureNotLike(String value) {
			addCriterion("picture not like", value, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureIn(List<String> values) {
			addCriterion("picture in", values, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureNotIn(List<String> values) {
			addCriterion("picture not in", values, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureBetween(String value1, String value2) {
			addCriterion("picture between", value1, value2, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureNotBetween(String value1, String value2) {
			addCriterion("picture not between", value1, value2, "picture");
			return (Criteria) this;
		}

		public Criteria andOrderUomIsNull() {
			addCriterion("order_uom is null");
			return (Criteria) this;
		}

		public Criteria andOrderUomIsNotNull() {
			addCriterion("order_uom is not null");
			return (Criteria) this;
		}

		public Criteria andOrderUomEqualTo(String value) {
			addCriterion("order_uom =", value, "orderUom");
			return (Criteria) this;
		}

		public Criteria andOrderUomNotEqualTo(String value) {
			addCriterion("order_uom <>", value, "orderUom");
			return (Criteria) this;
		}

		public Criteria andOrderUomGreaterThan(String value) {
			addCriterion("order_uom >", value, "orderUom");
			return (Criteria) this;
		}

		public Criteria andOrderUomGreaterThanOrEqualTo(String value) {
			addCriterion("order_uom >=", value, "orderUom");
			return (Criteria) this;
		}

		public Criteria andOrderUomLessThan(String value) {
			addCriterion("order_uom <", value, "orderUom");
			return (Criteria) this;
		}

		public Criteria andOrderUomLessThanOrEqualTo(String value) {
			addCriterion("order_uom <=", value, "orderUom");
			return (Criteria) this;
		}

		public Criteria andOrderUomLike(String value) {
			addCriterion("order_uom like", value, "orderUom");
			return (Criteria) this;
		}

		public Criteria andOrderUomNotLike(String value) {
			addCriterion("order_uom not like", value, "orderUom");
			return (Criteria) this;
		}

		public Criteria andOrderUomIn(List<String> values) {
			addCriterion("order_uom in", values, "orderUom");
			return (Criteria) this;
		}

		public Criteria andOrderUomNotIn(List<String> values) {
			addCriterion("order_uom not in", values, "orderUom");
			return (Criteria) this;
		}

		public Criteria andOrderUomBetween(String value1, String value2) {
			addCriterion("order_uom between", value1, value2, "orderUom");
			return (Criteria) this;
		}

		public Criteria andOrderUomNotBetween(String value1, String value2) {
			addCriterion("order_uom not between", value1, value2, "orderUom");
			return (Criteria) this;
		}

		public Criteria andOrderPriceIsNull() {
			addCriterion("order_price is null");
			return (Criteria) this;
		}

		public Criteria andOrderPriceIsNotNull() {
			addCriterion("order_price is not null");
			return (Criteria) this;
		}

		public Criteria andOrderPriceEqualTo(Double value) {
			addCriterion("order_price =", value, "orderPrice");
			return (Criteria) this;
		}

		public Criteria andOrderPriceNotEqualTo(Double value) {
			addCriterion("order_price <>", value, "orderPrice");
			return (Criteria) this;
		}

		public Criteria andOrderPriceGreaterThan(Double value) {
			addCriterion("order_price >", value, "orderPrice");
			return (Criteria) this;
		}

		public Criteria andOrderPriceGreaterThanOrEqualTo(Double value) {
			addCriterion("order_price >=", value, "orderPrice");
			return (Criteria) this;
		}

		public Criteria andOrderPriceLessThan(Double value) {
			addCriterion("order_price <", value, "orderPrice");
			return (Criteria) this;
		}

		public Criteria andOrderPriceLessThanOrEqualTo(Double value) {
			addCriterion("order_price <=", value, "orderPrice");
			return (Criteria) this;
		}

		public Criteria andOrderPriceIn(List<Double> values) {
			addCriterion("order_price in", values, "orderPrice");
			return (Criteria) this;
		}

		public Criteria andOrderPriceNotIn(List<Double> values) {
			addCriterion("order_price not in", values, "orderPrice");
			return (Criteria) this;
		}

		public Criteria andOrderPriceBetween(Double value1, Double value2) {
			addCriterion("order_price between", value1, value2, "orderPrice");
			return (Criteria) this;
		}

		public Criteria andOrderPriceNotBetween(Double value1, Double value2) {
			addCriterion("order_price not between", value1, value2, "orderPrice");
			return (Criteria) this;
		}

		public Criteria andSalePriceIsNull() {
			addCriterion("sale_price is null");
			return (Criteria) this;
		}

		public Criteria andSalePriceIsNotNull() {
			addCriterion("sale_price is not null");
			return (Criteria) this;
		}

		public Criteria andSalePriceEqualTo(Double value) {
			addCriterion("sale_price =", value, "salePrice");
			return (Criteria) this;
		}

		public Criteria andSalePriceNotEqualTo(Double value) {
			addCriterion("sale_price <>", value, "salePrice");
			return (Criteria) this;
		}

		public Criteria andSalePriceGreaterThan(Double value) {
			addCriterion("sale_price >", value, "salePrice");
			return (Criteria) this;
		}

		public Criteria andSalePriceGreaterThanOrEqualTo(Double value) {
			addCriterion("sale_price >=", value, "salePrice");
			return (Criteria) this;
		}

		public Criteria andSalePriceLessThan(Double value) {
			addCriterion("sale_price <", value, "salePrice");
			return (Criteria) this;
		}

		public Criteria andSalePriceLessThanOrEqualTo(Double value) {
			addCriterion("sale_price <=", value, "salePrice");
			return (Criteria) this;
		}

		public Criteria andSalePriceIn(List<Double> values) {
			addCriterion("sale_price in", values, "salePrice");
			return (Criteria) this;
		}

		public Criteria andSalePriceNotIn(List<Double> values) {
			addCriterion("sale_price not in", values, "salePrice");
			return (Criteria) this;
		}

		public Criteria andSalePriceBetween(Double value1, Double value2) {
			addCriterion("sale_price between", value1, value2, "salePrice");
			return (Criteria) this;
		}

		public Criteria andSalePriceNotBetween(Double value1, Double value2) {
			addCriterion("sale_price not between", value1, value2, "salePrice");
			return (Criteria) this;
		}

		public Criteria andBrandIsNull() {
			addCriterion("brand is null");
			return (Criteria) this;
		}

		public Criteria andBrandIsNotNull() {
			addCriterion("brand is not null");
			return (Criteria) this;
		}

		public Criteria andBrandEqualTo(String value) {
			addCriterion("brand =", value, "brand");
			return (Criteria) this;
		}

		public Criteria andBrandNotEqualTo(String value) {
			addCriterion("brand <>", value, "brand");
			return (Criteria) this;
		}

		public Criteria andBrandGreaterThan(String value) {
			addCriterion("brand >", value, "brand");
			return (Criteria) this;
		}

		public Criteria andBrandGreaterThanOrEqualTo(String value) {
			addCriterion("brand >=", value, "brand");
			return (Criteria) this;
		}

		public Criteria andBrandLessThan(String value) {
			addCriterion("brand <", value, "brand");
			return (Criteria) this;
		}

		public Criteria andBrandLessThanOrEqualTo(String value) {
			addCriterion("brand <=", value, "brand");
			return (Criteria) this;
		}

		public Criteria andBrandLike(String value) {
			addCriterion("brand like", value, "brand");
			return (Criteria) this;
		}

		public Criteria andBrandNotLike(String value) {
			addCriterion("brand not like", value, "brand");
			return (Criteria) this;
		}

		public Criteria andBrandIn(List<String> values) {
			addCriterion("brand in", values, "brand");
			return (Criteria) this;
		}

		public Criteria andBrandNotIn(List<String> values) {
			addCriterion("brand not in", values, "brand");
			return (Criteria) this;
		}

		public Criteria andBrandBetween(String value1, String value2) {
			addCriterion("brand between", value1, value2, "brand");
			return (Criteria) this;
		}

		public Criteria andBrandNotBetween(String value1, String value2) {
			addCriterion("brand not between", value1, value2, "brand");
			return (Criteria) this;
		}

		public Criteria andCreatedByIsNull() {
			addCriterion("created_by is null");
			return (Criteria) this;
		}

		public Criteria andCreatedByIsNotNull() {
			addCriterion("created_by is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedByEqualTo(String value) {
			addCriterion("created_by =", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotEqualTo(String value) {
			addCriterion("created_by <>", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByGreaterThan(String value) {
			addCriterion("created_by >", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
			addCriterion("created_by >=", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByLessThan(String value) {
			addCriterion("created_by <", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByLessThanOrEqualTo(String value) {
			addCriterion("created_by <=", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByLike(String value) {
			addCriterion("created_by like", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotLike(String value) {
			addCriterion("created_by not like", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByIn(List<String> values) {
			addCriterion("created_by in", values, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotIn(List<String> values) {
			addCriterion("created_by not in", values, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByBetween(String value1, String value2) {
			addCriterion("created_by between", value1, value2, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotBetween(String value1, String value2) {
			addCriterion("created_by not between", value1, value2, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedOnIsNull() {
			addCriterion("created_on is null");
			return (Criteria) this;
		}

		public Criteria andCreatedOnIsNotNull() {
			addCriterion("created_on is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedOnEqualTo(Date value) {
			addCriterion("created_on =", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnNotEqualTo(Date value) {
			addCriterion("created_on <>", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnGreaterThan(Date value) {
			addCriterion("created_on >", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnGreaterThanOrEqualTo(Date value) {
			addCriterion("created_on >=", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnLessThan(Date value) {
			addCriterion("created_on <", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnLessThanOrEqualTo(Date value) {
			addCriterion("created_on <=", value, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnIn(List<Date> values) {
			addCriterion("created_on in", values, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnNotIn(List<Date> values) {
			addCriterion("created_on not in", values, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnBetween(Date value1, Date value2) {
			addCriterion("created_on between", value1, value2, "createdOn");
			return (Criteria) this;
		}

		public Criteria andCreatedOnNotBetween(Date value1, Date value2) {
			addCriterion("created_on not between", value1, value2, "createdOn");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andIsBaseitemIsNull() {
			addCriterion("is_baseitem is null");
			return (Criteria) this;
		}

		public Criteria andIsBaseitemIsNotNull() {
			addCriterion("is_baseitem is not null");
			return (Criteria) this;
		}

		public Criteria andIsBaseitemEqualTo(Integer value) {
			addCriterion("is_baseitem =", value, "isBaseitem");
			return (Criteria) this;
		}

		public Criteria andIsBaseitemNotEqualTo(Integer value) {
			addCriterion("is_baseitem <>", value, "isBaseitem");
			return (Criteria) this;
		}

		public Criteria andIsBaseitemGreaterThan(Integer value) {
			addCriterion("is_baseitem >", value, "isBaseitem");
			return (Criteria) this;
		}

		public Criteria andIsBaseitemGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_baseitem >=", value, "isBaseitem");
			return (Criteria) this;
		}

		public Criteria andIsBaseitemLessThan(Integer value) {
			addCriterion("is_baseitem <", value, "isBaseitem");
			return (Criteria) this;
		}

		public Criteria andIsBaseitemLessThanOrEqualTo(Integer value) {
			addCriterion("is_baseitem <=", value, "isBaseitem");
			return (Criteria) this;
		}

		public Criteria andIsBaseitemIn(List<Integer> values) {
			addCriterion("is_baseitem in", values, "isBaseitem");
			return (Criteria) this;
		}

		public Criteria andIsBaseitemNotIn(List<Integer> values) {
			addCriterion("is_baseitem not in", values, "isBaseitem");
			return (Criteria) this;
		}

		public Criteria andIsBaseitemBetween(Integer value1, Integer value2) {
			addCriterion("is_baseitem between", value1, value2, "isBaseitem");
			return (Criteria) this;
		}

		public Criteria andIsBaseitemNotBetween(Integer value1, Integer value2) {
			addCriterion("is_baseitem not between", value1, value2, "isBaseitem");
			return (Criteria) this;
		}

		public Criteria andCodelistIsNull() {
			addCriterion("codelist is null");
			return (Criteria) this;
		}

		public Criteria andCodelistIsNotNull() {
			addCriterion("codelist is not null");
			return (Criteria) this;
		}

		public Criteria andCodelistEqualTo(String value) {
			addCriterion("codelist =", value, "codelist");
			return (Criteria) this;
		}

		public Criteria andCodelistNotEqualTo(String value) {
			addCriterion("codelist <>", value, "codelist");
			return (Criteria) this;
		}

		public Criteria andCodelistGreaterThan(String value) {
			addCriterion("codelist >", value, "codelist");
			return (Criteria) this;
		}

		public Criteria andCodelistGreaterThanOrEqualTo(String value) {
			addCriterion("codelist >=", value, "codelist");
			return (Criteria) this;
		}

		public Criteria andCodelistLessThan(String value) {
			addCriterion("codelist <", value, "codelist");
			return (Criteria) this;
		}

		public Criteria andCodelistLessThanOrEqualTo(String value) {
			addCriterion("codelist <=", value, "codelist");
			return (Criteria) this;
		}

		public Criteria andCodelistLike(String value) {
			addCriterion("codelist like", value, "codelist");
			return (Criteria) this;
		}

		public Criteria andCodelistNotLike(String value) {
			addCriterion("codelist not like", value, "codelist");
			return (Criteria) this;
		}

		public Criteria andCodelistIn(List<String> values) {
			addCriterion("codelist in", values, "codelist");
			return (Criteria) this;
		}

		public Criteria andCodelistNotIn(List<String> values) {
			addCriterion("codelist not in", values, "codelist");
			return (Criteria) this;
		}

		public Criteria andCodelistBetween(String value1, String value2) {
			addCriterion("codelist between", value1, value2, "codelist");
			return (Criteria) this;
		}

		public Criteria andCodelistNotBetween(String value1, String value2) {
			addCriterion("codelist not between", value1, value2, "codelist");
			return (Criteria) this;
		}

		public Criteria andSourceCodeIsNull() {
			addCriterion("source_code is null");
			return (Criteria) this;
		}

		public Criteria andSourceCodeIsNotNull() {
			addCriterion("source_code is not null");
			return (Criteria) this;
		}

		public Criteria andSourceCodeEqualTo(String value) {
			addCriterion("source_code =", value, "sourceCode");
			return (Criteria) this;
		}

		public Criteria andSourceCodeNotEqualTo(String value) {
			addCriterion("source_code <>", value, "sourceCode");
			return (Criteria) this;
		}

		public Criteria andSourceCodeGreaterThan(String value) {
			addCriterion("source_code >", value, "sourceCode");
			return (Criteria) this;
		}

		public Criteria andSourceCodeGreaterThanOrEqualTo(String value) {
			addCriterion("source_code >=", value, "sourceCode");
			return (Criteria) this;
		}

		public Criteria andSourceCodeLessThan(String value) {
			addCriterion("source_code <", value, "sourceCode");
			return (Criteria) this;
		}

		public Criteria andSourceCodeLessThanOrEqualTo(String value) {
			addCriterion("source_code <=", value, "sourceCode");
			return (Criteria) this;
		}

		public Criteria andSourceCodeLike(String value) {
			addCriterion("source_code like", value, "sourceCode");
			return (Criteria) this;
		}

		public Criteria andSourceCodeNotLike(String value) {
			addCriterion("source_code not like", value, "sourceCode");
			return (Criteria) this;
		}

		public Criteria andSourceCodeIn(List<String> values) {
			addCriterion("source_code in", values, "sourceCode");
			return (Criteria) this;
		}

		public Criteria andSourceCodeNotIn(List<String> values) {
			addCriterion("source_code not in", values, "sourceCode");
			return (Criteria) this;
		}

		public Criteria andSourceCodeBetween(String value1, String value2) {
			addCriterion("source_code between", value1, value2, "sourceCode");
			return (Criteria) this;
		}

		public Criteria andSourceCodeNotBetween(String value1, String value2) {
			addCriterion("source_code not between", value1, value2, "sourceCode");
			return (Criteria) this;
		}

		public Criteria andClassCodeIsNull() {
			addCriterion("class_code is null");
			return (Criteria) this;
		}

		public Criteria andClassCodeIsNotNull() {
			addCriterion("class_code is not null");
			return (Criteria) this;
		}

		public Criteria andClassCodeEqualTo(String value) {
			addCriterion("class_code =", value, "classCode");
			return (Criteria) this;
		}

		public Criteria andClassCodeNotEqualTo(String value) {
			addCriterion("class_code <>", value, "classCode");
			return (Criteria) this;
		}

		public Criteria andClassCodeGreaterThan(String value) {
			addCriterion("class_code >", value, "classCode");
			return (Criteria) this;
		}

		public Criteria andClassCodeGreaterThanOrEqualTo(String value) {
			addCriterion("class_code >=", value, "classCode");
			return (Criteria) this;
		}

		public Criteria andClassCodeLessThan(String value) {
			addCriterion("class_code <", value, "classCode");
			return (Criteria) this;
		}

		public Criteria andClassCodeLessThanOrEqualTo(String value) {
			addCriterion("class_code <=", value, "classCode");
			return (Criteria) this;
		}

		public Criteria andClassCodeLike(String value) {
			addCriterion("class_code like", value, "classCode");
			return (Criteria) this;
		}

		public Criteria andClassCodeNotLike(String value) {
			addCriterion("class_code not like", value, "classCode");
			return (Criteria) this;
		}

		public Criteria andClassCodeIn(List<String> values) {
			addCriterion("class_code in", values, "classCode");
			return (Criteria) this;
		}

		public Criteria andClassCodeNotIn(List<String> values) {
			addCriterion("class_code not in", values, "classCode");
			return (Criteria) this;
		}

		public Criteria andClassCodeBetween(String value1, String value2) {
			addCriterion("class_code between", value1, value2, "classCode");
			return (Criteria) this;
		}

		public Criteria andClassCodeNotBetween(String value1, String value2) {
			addCriterion("class_code not between", value1, value2, "classCode");
			return (Criteria) this;
		}

		public Criteria andSupplierIdIsNull() {
			addCriterion("supplier_id is null");
			return (Criteria) this;
		}

		public Criteria andSupplierIdIsNotNull() {
			addCriterion("supplier_id is not null");
			return (Criteria) this;
		}

		public Criteria andSupplierIdEqualTo(String value) {
			addCriterion("supplier_id =", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdNotEqualTo(String value) {
			addCriterion("supplier_id <>", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdGreaterThan(String value) {
			addCriterion("supplier_id >", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdGreaterThanOrEqualTo(String value) {
			addCriterion("supplier_id >=", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdLessThan(String value) {
			addCriterion("supplier_id <", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdLessThanOrEqualTo(String value) {
			addCriterion("supplier_id <=", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdLike(String value) {
			addCriterion("supplier_id like", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdNotLike(String value) {
			addCriterion("supplier_id not like", value, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdIn(List<String> values) {
			addCriterion("supplier_id in", values, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdNotIn(List<String> values) {
			addCriterion("supplier_id not in", values, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdBetween(String value1, String value2) {
			addCriterion("supplier_id between", value1, value2, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierIdNotBetween(String value1, String value2) {
			addCriterion("supplier_id not between", value1, value2, "supplierId");
			return (Criteria) this;
		}

		public Criteria andSupplierNameIsNull() {
			addCriterion("supplier_name is null");
			return (Criteria) this;
		}

		public Criteria andSupplierNameIsNotNull() {
			addCriterion("supplier_name is not null");
			return (Criteria) this;
		}

		public Criteria andSupplierNameEqualTo(String value) {
			addCriterion("supplier_name =", value, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameNotEqualTo(String value) {
			addCriterion("supplier_name <>", value, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameGreaterThan(String value) {
			addCriterion("supplier_name >", value, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameGreaterThanOrEqualTo(String value) {
			addCriterion("supplier_name >=", value, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameLessThan(String value) {
			addCriterion("supplier_name <", value, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameLessThanOrEqualTo(String value) {
			addCriterion("supplier_name <=", value, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameLike(String value) {
			addCriterion("supplier_name like", value, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameNotLike(String value) {
			addCriterion("supplier_name not like", value, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameIn(List<String> values) {
			addCriterion("supplier_name in", values, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameNotIn(List<String> values) {
			addCriterion("supplier_name not in", values, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameBetween(String value1, String value2) {
			addCriterion("supplier_name between", value1, value2, "supplierName");
			return (Criteria) this;
		}

		public Criteria andSupplierNameNotBetween(String value1, String value2) {
			addCriterion("supplier_name not between", value1, value2, "supplierName");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table splititemview
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table splititemview
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 21 23:58:22 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}