package com.wecloud.erp.model;

public class UomFormula {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uomformula.ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uomformula.NAME
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uomformula.BASE_UOM
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String baseUom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uomformula.FROM_UOM
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private String fromUom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uomformula.rate
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	private Double rate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uomformula.ID
	 * @return  the value of uomformula.ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uomformula.ID
	 * @param id  the value for uomformula.ID
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uomformula.NAME
	 * @return  the value of uomformula.NAME
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uomformula.NAME
	 * @param name  the value for uomformula.NAME
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uomformula.BASE_UOM
	 * @return  the value of uomformula.BASE_UOM
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getBaseUom() {
		return baseUom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uomformula.BASE_UOM
	 * @param baseUom  the value for uomformula.BASE_UOM
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setBaseUom(String baseUom) {
		this.baseUom = baseUom == null ? null : baseUom.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uomformula.FROM_UOM
	 * @return  the value of uomformula.FROM_UOM
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public String getFromUom() {
		return fromUom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uomformula.FROM_UOM
	 * @param fromUom  the value for uomformula.FROM_UOM
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setFromUom(String fromUom) {
		this.fromUom = fromUom == null ? null : fromUom.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uomformula.rate
	 * @return  the value of uomformula.rate
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public Double getRate() {
		return rate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uomformula.rate
	 * @param rate  the value for uomformula.rate
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	public void setRate(Double rate) {
		this.rate = rate;
	}
}