package com.wecloud.erp.persistence.dao;

import com.wecloud.erp.model.CheckoutRequest;
import com.wecloud.erp.model.CheckoutRequestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CheckoutRequestMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int countByExample(CheckoutRequestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int deleteByExample(CheckoutRequestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insert(CheckoutRequest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insertSelective(CheckoutRequest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	List<CheckoutRequest> selectByExampleWithBLOBs(CheckoutRequestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	List<CheckoutRequest> selectByExample(CheckoutRequestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	CheckoutRequest selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExampleSelective(@Param("record") CheckoutRequest record,
			@Param("example") CheckoutRequestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") CheckoutRequest record,
			@Param("example") CheckoutRequestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExample(@Param("record") CheckoutRequest record, @Param("example") CheckoutRequestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByPrimaryKeySelective(CheckoutRequest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByPrimaryKeyWithBLOBs(CheckoutRequest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByPrimaryKey(CheckoutRequest record);
}