package com.wecloud.erp.persistence.dao;

import com.wecloud.erp.model.CheckinRecord;
import com.wecloud.erp.model.CheckinRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CheckinRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkinrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int countByExample(CheckinRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkinrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int deleteByExample(CheckinRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkinrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkinrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insert(CheckinRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkinrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insertSelective(CheckinRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkinrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	List<CheckinRecord> selectByExampleWithBLOBs(CheckinRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkinrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	List<CheckinRecord> selectByExample(CheckinRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkinrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	CheckinRecord selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkinrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExampleSelective(@Param("record") CheckinRecord record, @Param("example") CheckinRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkinrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") CheckinRecord record, @Param("example") CheckinRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkinrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExample(@Param("record") CheckinRecord record, @Param("example") CheckinRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkinrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByPrimaryKeySelective(CheckinRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkinrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByPrimaryKeyWithBLOBs(CheckinRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkinrecord
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByPrimaryKey(CheckinRecord record);
}