package com.wecloud.erp.persistence.dao;

import com.wecloud.erp.model.CheckoutRecordItem;
import com.wecloud.erp.model.CheckoutRecordItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CheckoutRecordItemMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutrecorditem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int countByExample(CheckoutRecordItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutrecorditem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int deleteByExample(CheckoutRecordItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutrecorditem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutrecorditem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insert(CheckoutRecordItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutrecorditem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insertSelective(CheckoutRecordItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutrecorditem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	List<CheckoutRecordItem> selectByExample(CheckoutRecordItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutrecorditem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	CheckoutRecordItem selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutrecorditem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExampleSelective(@Param("record") CheckoutRecordItem record,
			@Param("example") CheckoutRecordItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutrecorditem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExample(@Param("record") CheckoutRecordItem record,
			@Param("example") CheckoutRecordItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutrecorditem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByPrimaryKeySelective(CheckoutRecordItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutrecorditem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByPrimaryKey(CheckoutRecordItem record);
}