package com.wecloud.erp.persistence.dao;

import com.wecloud.erp.model.CheckoutReqItem;
import com.wecloud.erp.model.CheckoutReqItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CheckoutReqItemMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutreqitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int countByExample(CheckoutReqItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutreqitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int deleteByExample(CheckoutReqItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutreqitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutreqitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insert(CheckoutReqItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutreqitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insertSelective(CheckoutReqItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutreqitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	List<CheckoutReqItem> selectByExample(CheckoutReqItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutreqitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	CheckoutReqItem selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutreqitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExampleSelective(@Param("record") CheckoutReqItem record,
			@Param("example") CheckoutReqItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutreqitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExample(@Param("record") CheckoutReqItem record, @Param("example") CheckoutReqItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutreqitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByPrimaryKeySelective(CheckoutReqItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table checkoutreqitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByPrimaryKey(CheckoutReqItem record);
}