package com.wecloud.erp.persistence.dao;

import com.wecloud.erp.model.ItemSupplierMapping;
import com.wecloud.erp.model.ItemSupplierMappingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemSupplierMappingMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemsuppliermapping
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int countByExample(ItemSupplierMappingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemsuppliermapping
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int deleteByExample(ItemSupplierMappingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemsuppliermapping
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insert(ItemSupplierMapping record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemsuppliermapping
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insertSelective(ItemSupplierMapping record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemsuppliermapping
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	List<ItemSupplierMapping> selectByExample(ItemSupplierMappingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemsuppliermapping
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExampleSelective(@Param("record") ItemSupplierMapping record,
			@Param("example") ItemSupplierMappingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemsuppliermapping
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExample(@Param("record") ItemSupplierMapping record,
			@Param("example") ItemSupplierMappingExample example);
}