package com.wecloud.erp.persistence.dao;

import com.wecloud.erp.model.Item;
import com.wecloud.erp.model.ItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table item
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int countByExample(ItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table item
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int deleteByExample(ItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table item
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table item
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insert(Item record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table item
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insertSelective(Item record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table item
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	List<Item> selectByExampleWithBLOBs(ItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table item
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	List<Item> selectByExample(ItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table item
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	Item selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table item
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExampleSelective(@Param("record") Item record, @Param("example") ItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table item
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") Item record, @Param("example") ItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table item
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExample(@Param("record") Item record, @Param("example") ItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table item
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByPrimaryKeySelective(Item record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table item
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByPrimaryKeyWithBLOBs(Item record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table item
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByPrimaryKey(Item record);
}