package com.wecloud.erp.persistence.dao;

import com.wecloud.erp.model.ItemSummary;
import com.wecloud.erp.model.ItemSummaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemSummaryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemsummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int countByExample(ItemSummaryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemsummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int deleteByExample(ItemSummaryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemsummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insert(ItemSummary record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemsummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insertSelective(ItemSummary record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemsummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	List<ItemSummary> selectByExample(ItemSummaryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemsummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExampleSelective(@Param("record") ItemSummary record, @Param("example") ItemSummaryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemsummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExample(@Param("record") ItemSummary record, @Param("example") ItemSummaryExample example);
}