package com.wecloud.erp.persistence.dao;

import com.wecloud.erp.model.ItemStorage;
import com.wecloud.erp.model.ItemStorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemStorageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemstorage
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int countByExample(ItemStorageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemstorage
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int deleteByExample(ItemStorageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemstorage
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insert(ItemStorage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemstorage
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insertSelective(ItemStorage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemstorage
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	List<ItemStorage> selectByExample(ItemStorageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemstorage
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExampleSelective(@Param("record") ItemStorage record, @Param("example") ItemStorageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table itemstorage
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExample(@Param("record") ItemStorage record, @Param("example") ItemStorageExample example);
}