package com.wecloud.erp.persistence.dao;

import com.wecloud.erp.model.OrderRequest;
import com.wecloud.erp.model.OrderRequestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderRequestMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int countByExample(OrderRequestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int deleteByExample(OrderRequestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insert(OrderRequest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insertSelective(OrderRequest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	List<OrderRequest> selectByExampleWithBLOBs(OrderRequestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	List<OrderRequest> selectByExample(OrderRequestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	OrderRequest selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExampleSelective(@Param("record") OrderRequest record, @Param("example") OrderRequestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") OrderRequest record, @Param("example") OrderRequestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExample(@Param("record") OrderRequest record, @Param("example") OrderRequestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByPrimaryKeySelective(OrderRequest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByPrimaryKeyWithBLOBs(OrderRequest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderrequest
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByPrimaryKey(OrderRequest record);
}