package com.wecloud.erp.persistence.dao;

import com.wecloud.erp.model.PoReturn;
import com.wecloud.erp.model.PoReturnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PoReturnMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table poreturn
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int countByExample(PoReturnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table poreturn
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int deleteByExample(PoReturnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table poreturn
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table poreturn
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insert(PoReturn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table poreturn
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insertSelective(PoReturn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table poreturn
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	List<PoReturn> selectByExampleWithBLOBs(PoReturnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table poreturn
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	List<PoReturn> selectByExample(PoReturnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table poreturn
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	PoReturn selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table poreturn
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExampleSelective(@Param("record") PoReturn record, @Param("example") PoReturnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table poreturn
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") PoReturn record, @Param("example") PoReturnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table poreturn
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExample(@Param("record") PoReturn record, @Param("example") PoReturnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table poreturn
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByPrimaryKeySelective(PoReturn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table poreturn
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByPrimaryKeyWithBLOBs(PoReturn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table poreturn
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByPrimaryKey(PoReturn record);
}