package com.wecloud.erp.persistence.dao;

import com.wecloud.erp.model.PoSummary;
import com.wecloud.erp.model.PoSummaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PoSummaryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int countByExample(PoSummaryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int deleteByExample(PoSummaryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insert(PoSummary record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insertSelective(PoSummary record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	List<PoSummary> selectByExample(PoSummaryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExampleSelective(@Param("record") PoSummary record, @Param("example") PoSummaryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table posummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExample(@Param("record") PoSummary record, @Param("example") PoSummaryExample example);
}