package com.wecloud.erp.persistence.dao;

import com.wecloud.erp.model.SoItem;
import com.wecloud.erp.model.SoItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SoItemMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table soitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int countByExample(SoItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table soitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int deleteByExample(SoItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table soitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table soitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insert(SoItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table soitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insertSelective(SoItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table soitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	List<SoItem> selectByExampleWithBLOBs(SoItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table soitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	List<SoItem> selectByExample(SoItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table soitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	SoItem selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table soitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExampleSelective(@Param("record") SoItem record, @Param("example") SoItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table soitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") SoItem record, @Param("example") SoItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table soitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExample(@Param("record") SoItem record, @Param("example") SoItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table soitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByPrimaryKeySelective(SoItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table soitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByPrimaryKeyWithBLOBs(SoItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table soitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByPrimaryKey(SoItem record);
}