package com.wecloud.erp.persistence.dao;

import com.wecloud.erp.model.SoReturnItem;
import com.wecloud.erp.model.SoReturnItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SoReturnItemMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table soreturnitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int countByExample(SoReturnItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table soreturnitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int deleteByExample(SoReturnItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table soreturnitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table soreturnitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insert(SoReturnItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table soreturnitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insertSelective(SoReturnItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table soreturnitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	List<SoReturnItem> selectByExample(SoReturnItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table soreturnitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	SoReturnItem selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table soreturnitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExampleSelective(@Param("record") SoReturnItem record, @Param("example") SoReturnItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table soreturnitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExample(@Param("record") SoReturnItem record, @Param("example") SoReturnItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table soreturnitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByPrimaryKeySelective(SoReturnItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table soreturnitem
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByPrimaryKey(SoReturnItem record);
}