package com.wecloud.erp.persistence.dao;

import com.wecloud.erp.model.SoSummary;
import com.wecloud.erp.model.SoSummaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SoSummaryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sosummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int countByExample(SoSummaryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sosummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int deleteByExample(SoSummaryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sosummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insert(SoSummary record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sosummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int insertSelective(SoSummary record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sosummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	List<SoSummary> selectByExample(SoSummaryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sosummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExampleSelective(@Param("record") SoSummary record, @Param("example") SoSummaryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sosummary
	 * @mbggenerated  Sat Apr 23 10:00:33 HKT 2016
	 */
	int updateByExample(@Param("record") SoSummary record, @Param("example") SoSummaryExample example);
}